//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtensive.Storage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtensive.Storage.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Model.
        /// </summary>
        internal static string ActualModel {
            get {
                return ResourceManager.GetString("ActualModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: multiple attributes of type &apos;{1}&apos; are not allowed here..
        /// </summary>
        internal static string AspectExMultipleAttributesOfTypeXAreNotAllowedHere {
            get {
                return ResourceManager.GetString("AspectExMultipleAttributesOfTypeXAreNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associations.
        /// </summary>
        internal static string Associations {
            get {
                return ResourceManager.GetString("Associations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Definitions.
        /// </summary>
        internal static string CustomDefinitions {
            get {
                return ResourceManager.GetString("CustomDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active serialization context is not found..
        /// </summary>
        internal static string ExActiveSerializationContextIsNotFound {
            get {
                return ResourceManager.GetString("ExActiveSerializationContextIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual schema version of assembly &apos;{0}&apos; is expected to be &apos;{1}&apos;, but currently it is &apos;{2}&apos;..
        /// </summary>
        internal static string ExActualSchemaVersionOfAssemblyXIsExpectedToBeYButCurrentlyItIsZ {
            get {
                return ResourceManager.GetString("ExActualSchemaVersionOfAssemblyXIsExpectedToBeYButCurrentlyItIsZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association multiplicity &apos;{0}&apos; is not valid for field &apos;{1}&apos;.
        /// </summary>
        internal static string ExAssociationMultiplicityIsNotValidForField {
            get {
                return ResourceManager.GetString("ExAssociationMultiplicityIsNotValidForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary expressions with NodeType = &apos;ExpressionType.{0}&apos; aren&apos;t supported..
        /// </summary>
        internal static string ExBinaryExpressionsWithNodeTypeXAreNotSupported {
            get {
                return ResourceManager.GetString("ExBinaryExpressionsWithNodeTypeXAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to associate non-empty EntityState with Key of unknown type..
        /// </summary>
        internal static string ExCannotAssociateNonEmptyEntityStateWithKeyOfUnknownType {
            get {
                return ResourceManager.GetString("ExCannotAssociateNonEmptyEntityStateWithKeyOfUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot commit a transaction: ValidationContext is in inconsistent state..
        /// </summary>
        internal static string ExCannotCommitATransactionValidationContextIsInInconsistentState {
            get {
                return ResourceManager.GetString("ExCannotCommitATransactionValidationContextIsInInconsistentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a hanlder of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExCannotFindHandlerOfTypeX {
            get {
                return ResourceManager.GetString("ExCannotFindHandlerOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get validation context: there is no active transaction..
        /// </summary>
        internal static string ExCanNotGetValidationContextThereIsNoActiveTransaction {
            get {
                return ResourceManager.GetString("ExCanNotGetValidationContextThereIsNoActiveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open a transaction: there is no current Session..
        /// </summary>
        internal static string ExCanNotOpenTransactionNoCurrentSession {
            get {
                return ResourceManager.GetString("ExCanNotOpenTransactionNoCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve entity with key &apos;{0}&apos;.
        /// </summary>
        internal static string ExCannotResolveEntityWithKeyX {
            get {
                return ResourceManager.GetString("ExCannotResolveEntityWithKeyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upgrade schema safely..
        /// </summary>
        internal static string ExCannotUpgradeSchemaSafely {
            get {
                return ResourceManager.GetString("ExCannotUpgradeSchemaSafely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use default generator for complex Keys..
        /// </summary>
        internal static string ExCannotUseDefaultGeneratorForComplexKeys {
            get {
                return ResourceManager.GetString("ExCannotUseDefaultGeneratorForComplexKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value length {0} greater than column Length {1}. .
        /// </summary>
        internal static string ExColumnLength {
            get {
                return ResourceManager.GetString("ExColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assign null to not-nullable column..
        /// </summary>
        internal static string ExColumnNotNullable {
            get {
                return ResourceManager.GetString("ExColumnNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; is not found..
        /// </summary>
        internal static string ExColumnXIsNotFound {
            get {
                return ResourceManager.GetString("ExColumnXIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer for type &apos;{0}&apos; is not available..
        /// </summary>
        internal static string ExComparerForTypeIsNotAvailable {
            get {
                return ResourceManager.GetString("ExComparerForTypeIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;CompilerContainer&apos; attribute isn&apos;t applied to type &apos;{0}&apos;..
        /// </summary>
        internal static string ExCompilerContainerAttributeIsNotAppliedToTypeX {
            get {
                return ResourceManager.GetString("ExCompilerContainerAttributeIsNotAppliedToTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration for Domain with name &apos;{0}&apos; is not found in application configuration file (section &apos;{1}&apos;)..
        /// </summary>
        internal static string ExConfigurationForDomainIsNotFoundInApplicationConfigurationFile {
            get {
                return ResourceManager.GetString("ExConfigurationForDomainIsNotFoundInApplicationConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint violation: constraint {0} on field &apos;{1}.{2}&apos; of object &apos;{3}&apos; failed on value {4}..
        /// </summary>
        internal static string ExConstraintViolation {
            get {
                return ResourceManager.GetString("ExConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find anonymous mapping for field &apos;{0}&apos;..
        /// </summary>
        internal static string ExCouldNotFindAnonymousMappingForFieldX {
            get {
                return ResourceManager.GetString("ExCouldNotFindAnonymousMappingForFieldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find entity mapping for field &apos;{0}&apos;..
        /// </summary>
        internal static string ExCouldNotFindEntityMappingForFieldX {
            get {
                return ResourceManager.GetString("ExCouldNotFindEntityMappingForFieldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find field segment for field &apos;{0}&apos;..
        /// </summary>
        internal static string ExCouldNotFindFieldSegmentForFieldX {
            get {
                return ResourceManager.GetString("ExCouldNotFindFieldSegmentForFieldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find grouping mapping for field &apos;{0}&apos;..
        /// </summary>
        internal static string ExCouldNotFindGroupingMappingForFieldX {
            get {
                return ResourceManager.GetString("ExCouldNotFindGroupingMappingForFieldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find subquery mapping for field &apos;{0}&apos;..
        /// </summary>
        internal static string ExCouldNotFindSubqueryMappingForFieldX {
            get {
                return ResourceManager.GetString("ExCouldNotFindSubqueryMappingForFieldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load types from assembly {0}..
        /// </summary>
        internal static string ExCouldNotLoadTypesFromAssembly {
            get {
                return ResourceManager.GetString("ExCouldNotLoadTypesFromAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default generator can serve hierarchy with exactly one key field..
        /// </summary>
        internal static string ExDefaultGeneratorCanServeHierarchyWithExactlyOneKeyField {
            get {
                return ResourceManager.GetString("ExDefaultGeneratorCanServeHierarchyWithExactlyOneKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate assembly name: {0}..
        /// </summary>
        internal static string ExDuplicateAssemblyNameX {
            get {
                return ResourceManager.GetString("ExDuplicateAssemblyNameX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element with name &apos;{0}&apos; is contained in this instance already..
        /// </summary>
        internal static string ExElementWithNameContainedInThisInstanceAlready {
            get {
                return ResourceManager.GetString("ExElementWithNameContainedInThisInstanceAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element with type {0} is contained in this instance already..
        /// </summary>
        internal static string ExElementWithTypeIsContainedInThisInstanceAlready {
            get {
                return ResourceManager.GetString("ExElementWithTypeIsContainedInThisInstanceAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity is in inconsistent state..
        /// </summary>
        internal static string ExEntityIsInInconsistentState {
            get {
                return ResourceManager.GetString("ExEntityIsInInconsistentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity is removed..
        /// </summary>
        internal static string ExEntityIsRemoved {
            get {
                return ResourceManager.GetString("ExEntityIsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify removed entity..
        /// </summary>
        internal static string ExEntityRemoved {
            get {
                return ResourceManager.GetString("ExEntityRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitySet can&apos;t be assigned.
        /// </summary>
        internal static string ExEntitySetCanTBeAssigned {
            get {
                return ResourceManager.GetString("ExEntitySetCanTBeAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity set is invalid due to current transaction is not active..
        /// </summary>
        internal static string ExEntitySetInvalidBecauseTransactionIsNotActive {
            get {
                return ResourceManager.GetString("ExEntitySetInvalidBecauseTransactionIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &apos;{0}&apos; is bound to another session..
        /// </summary>
        internal static string ExEntityXIsBoundToAnotherSession {
            get {
                return ResourceManager.GetString("ExEntityXIsBoundToAnotherSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors have been occurred during storage build. See error log for details..
        /// </summary>
        internal static string ExErrorsDuringStorageBuild {
            get {
                return ResourceManager.GetString("ExErrorsDuringStorageBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression of type &apos;{0}&apos; is not a sequence.
        /// </summary>
        internal static string ExExpressionOfTypeXIsNotASequence {
            get {
                return ResourceManager.GetString("ExExpressionOfTypeXIsNotASequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted schema is not compatible with the target schema..
        /// </summary>
        internal static string ExExtractedSchemaIsNotCompatibleWithTheTargetSchema {
            get {
                return ResourceManager.GetString("ExExtractedSchemaIsNotCompatibleWithTheTargetSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted schema is not equal to the target schemal..
        /// </summary>
        internal static string ExExtractedSchemaIsNotEqualToTheTargetSchema {
            get {
                return ResourceManager.GetString("ExExtractedSchemaIsNotEqualToTheTargetSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not an Entity field in Type &apos;{1}&apos;..
        /// </summary>
        internal static string ExFieldIsNotAnEntityField {
            get {
                return ResourceManager.GetString("ExFieldIsNotAnEntityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} not found in model..
        /// </summary>
        internal static string ExFieldNotFoundInModel {
            get {
                return ResourceManager.GetString("ExFieldNotFoundInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with name &apos;{0}&apos; already exists in Entity.Fields collection..
        /// </summary>
        internal static string ExFieldWithNameAlreadyExistsInEntityFieldsCollection {
            get {
                return ResourceManager.GetString("ExFieldWithNameAlreadyExistsInEntityFieldsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with name &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string ExFieldWithNameXIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("ExFieldWithNameXIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; can&apos;t have LazyLoad attribute as it is included in primary key..
        /// </summary>
        internal static string ExFieldXCanTBeLoadOnDemandAsItIsIncludedInPrimaryKey {
            get {
                return ResourceManager.GetString("ExFieldXCanTBeLoadOnDemandAsItIsIncludedInPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; can&apos;t be Nullable as it is included in primary key..
        /// </summary>
        internal static string ExFieldXCanTBeNullableAsItIsIncludedInPrimaryKey {
            get {
                return ResourceManager.GetString("ExFieldXCanTBeNullableAsItIsIncludedInPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} has &apos;{1}&apos; type but is marked as not nullable..
        /// </summary>
        internal static string ExFieldXHasYTypeButIsMarkedAsNotNullable {
            get {
                return ResourceManager.GetString("ExFieldXHasYTypeButIsMarkedAsNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is already defined in type {1} or its ancestor..
        /// </summary>
        internal static string ExFieldXIsAlreadyDefinedInTypeXOrItsAncestor {
            get {
                return ResourceManager.GetString("ExFieldXIsAlreadyDefinedInTypeXOrItsAncestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}.{1}&apos; is not found..
        /// </summary>
        internal static string ExFieldXYIsNotFound {
            get {
                return ResourceManager.GetString("ExFieldXYIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index already contains field &apos;{0}&apos;..
        /// </summary>
        internal static string ExIndexAlreadyContainsField {
            get {
                return ResourceManager.GetString("ExIndexAlreadyContainsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexed properties are not supported..
        /// </summary>
        internal static string ExIndexedPropertiesAreNotSupported {
            get {
                return ResourceManager.GetString("ExIndexedPropertiesAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index field &apos;{0}&apos; is incorrect..
        /// </summary>
        internal static string ExIndexFieldXIsIncorrect {
            get {
                return ResourceManager.GetString("ExIndexFieldXIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must contain at least one field..
        /// </summary>
        internal static string ExIndexMustContainAtLeastOneField {
            get {
                return ResourceManager.GetString("ExIndexMustContainAtLeastOneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ExIndexNameXIsInvalid {
            get {
                return ResourceManager.GetString("ExIndexNameXIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index with name &apos;{0}&apos; already exists in EntityInfo.Indexes collection..
        /// </summary>
        internal static string ExIndexWithNameAlreadyExistsInEntityInfoIndexesCollection {
            get {
                return ResourceManager.GetString("ExIndexWithNameAlreadyExistsInEntityInfoIndexesCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index with name &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string ExIndexWithNameXIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("ExIndexWithNameXIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface &apos;{0}&apos; does not belong to &apos;{1}&apos; hierarchy..
        /// </summary>
        internal static string ExInterfaceXDoesNotBelongToXHierarchy {
            get {
                return ResourceManager.GetString("ExInterfaceXDoesNotBelongToXHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field value, constraint {0} is violated..
        /// </summary>
        internal static string ExInvalidFieldValueConstraintXIsViolated {
            get {
                return ResourceManager.GetString("ExInvalidFieldValueConstraintXIsViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fill factor &apos;{0}&apos;. Value must be between 0 and 1..
        /// </summary>
        internal static string ExInvalidFillFactorXValueMustBeBetween0And1 {
            get {
                return ResourceManager.GetString("ExInvalidFillFactorXValueMustBeBetween0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create key. Key params do not correspond to key structure..
        /// </summary>
        internal static string ExInvalidKeyParams {
            get {
                return ResourceManager.GetString("ExInvalidKeyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String representaion of the Key has invalid format..
        /// </summary>
        internal static string ExInvalidKeyString {
            get {
                return ResourceManager.GetString("ExInvalidKeyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;Length&apos; attribute on &apos;{0}&apos; field..
        /// </summary>
        internal static string ExInvalidLengthAttributeOnXField {
            get {
                return ResourceManager.GetString("ExInvalidLengthAttributeOnXField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mapping name &apos;{0}&apos;..
        /// </summary>
        internal static string ExInvalidMappingNameX {
            get {
                return ResourceManager.GetString("ExInvalidMappingNameX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;OnDelete&apos; attribute usage on field &apos;{0}&apos;. Field is not entity reference..
        /// </summary>
        internal static string ExInvalidOnDeleteAttributeUsageOnFieldXFieldIsNotEntityReference {
            get {
                return ResourceManager.GetString("ExInvalidOnDeleteAttributeUsageOnFieldXFieldIsNotEntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Session of specified ISessionBound object is invalid..
        /// </summary>
        internal static string ExInvalidSession {
            get {
                return ResourceManager.GetString("ExInvalidSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid upgrader version.
        /// </summary>
        internal static string ExInvalidUpgraderVersion {
            get {
                return ResourceManager.GetString("ExInvalidUpgraderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found in EntitySet.
        /// </summary>
        internal static string ExItemNotFoundInEntitySet {
            get {
                return ResourceManager.GetString("ExItemNotFoundInEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key can not be null..
        /// </summary>
        internal static string ExKeyCanNotBeNull {
            get {
                return ResourceManager.GetString("ExKeyCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key property &apos;{0}&apos; declared at &apos;{1}&apos; should not have public or protected set accessor. Use  base protected constructor instead..
        /// </summary>
        internal static string ExKeyFieldXInTypeYShouldNotHaveSetAccessor {
            get {
                return ResourceManager.GetString("ExKeyFieldXInTypeYShouldNotHaveSetAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key field &apos;{0}&apos; was not found in type &apos;{1}&apos;..
        /// </summary>
        internal static string ExKeyFieldXWasNotFoundInTypeY {
            get {
                return ResourceManager.GetString("ExKeyFieldXWasNotFoundInTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key provider &apos;{0}&apos; and hierarchy {1} key field amount mismatch..
        /// </summary>
        internal static string ExKeyProviderXAndHierarchyYKeyFieldAmountMismatch {
            get {
                return ResourceManager.GetString("ExKeyProviderXAndHierarchyYKeyFieldAmountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key provider &apos;{0}&apos; should define at least one key field..
        /// </summary>
        internal static string ExKeyProviderXShouldDefineAtLeastOneKeyField {
            get {
                return ResourceManager.GetString("ExKeyProviderXShouldDefineAtLeastOneKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; was not found in storage..
        /// </summary>
        internal static string ExKeyXWasNotFoundInStorage {
            get {
                return ResourceManager.GetString("ExKeyXWasNotFoundInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Length&apos; constraint violation on field &apos;{0}&apos;.
        /// </summary>
        internal static string ExLengthConstraintViolationOnFieldX {
            get {
                return ResourceManager.GetString("ExLengthConstraintViolationOnFieldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master association &apos;{0}&apos; is already paired with &apos;{1}&apos;.
        /// </summary>
        internal static string ExMasterAssociationIsAlreadyPaired {
            get {
                return ResourceManager.GetString("ExMasterAssociationIsAlreadyPaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one enabled {0} is provided for assembly &quot;{1}&quot;..
        /// </summary>
        internal static string ExMoreThanOneEnabledXIsProvidedForAssemblyY {
            get {
                return ResourceManager.GetString("ExMoreThanOneEnabledXIsProvidedForAssemblyY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {0} is invalid..
        /// </summary>
        internal static string ExNameXIsInvalid {
            get {
                return ResourceManager.GetString("ExNameXIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current Session..
        /// </summary>
        internal static string ExNoCurrentSession {
            get {
                return ResourceManager.GetString("ExNoCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;NotNullable&apos; constraint violation on field &apos;{0}&apos;.
        /// </summary>
        internal static string ExNotNullableConstraintViolationOnFieldX {
            get {
                return ResourceManager.GetString("ExNotNullableConstraintViolationOnFieldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upgrade handler is found for assembly &quot;{0}&quot;, version {1}..
        /// </summary>
        internal static string ExNoUpgradeHandlerIsFoundForAssemblyXVersionY {
            get {
                return ResourceManager.GetString("ExNoUpgradeHandlerIsFoundForAssemblyXVersionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only equality ranges are supported..
        /// </summary>
        internal static string ExOnlyEqualityRangesAreSupported {
            get {
                return ResourceManager.GetString("ExOnlyEqualityRangesAreSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object outside of initial transaction scope..
        /// </summary>
        internal static string ExOutOfTransactionScope {
            get {
                return ResourceManager.GetString("ExOutOfTransactionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired field &apos;{0}&apos; has wrong type. It should be reference to Entity or a EntitySet..
        /// </summary>
        internal static string ExPairedFieldXHasWrongTypeItShouldBeReferenceToEntityOrAEntitySet {
            get {
                return ResourceManager.GetString("ExPairedFieldXHasWrongTypeItShouldBeReferenceToEntityOrAEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired field &apos;{0}&apos; was not found in &apos;{1}&apos; type..
        /// </summary>
        internal static string ExPairedFieldXWasNotFoundInYType {
            get {
                return ResourceManager.GetString("ExPairedFieldXWasNotFoundInYType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;PairTo&apos; attribute can not be applied to field &apos;{0}&apos; of type &apos;{1}&apos;. It is already applied to field &apos;{2}&apos; of type &apos;{3}&apos;..
        /// </summary>
        internal static string ExPairToAttributeCanNotBeAppliedToXField {
            get {
                return ResourceManager.GetString("ExPairToAttributeCanNotBeAppliedToXField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;PairTo&apos; attribute can not be used with &apos;{0}&apos; field..
        /// </summary>
        internal static string ExPairToAttributeCanNotBeUsedWithXField {
            get {
                return ResourceManager.GetString("ExPairToAttributeCanNotBeUsedWithXField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent attribute isn&apos;t applied. Add to AssemblyInfo.cs (in &quot;{0}&quot; assembly) following line: [assembly: Persistent(AttributeTargetAssemblies = &quot;{0}&quot;)].
        /// </summary>
        internal static string ExPersistentAttributeIsNotSetOnTypeX {
            get {
                return ResourceManager.GetString("ExPersistentAttributeIsNotSetOnTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit &apos;IsNullable&apos; attribute is redundant.
        /// </summary>
        internal static string ExplicitIsNullableAttributeIsRedundant {
            get {
                return ResourceManager.GetString("ExplicitIsNullableAttributeIsRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit &apos;LazyLoad&apos; attribute on field &apos;{0}&apos; is redundant.
        /// </summary>
        internal static string ExplicitLazyLoadAttributeOnFieldXIsRedundant {
            get {
                return ResourceManager.GetString("ExplicitLazyLoadAttributeOnFieldXIsRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit mapping name setting is redundant. The same name &apos;{0}&apos; will be generated automatically..
        /// </summary>
        internal static string ExplicitMappingNameSettingIsRedundantTheSameNameXWillBeGeneratedAutomatically {
            get {
                return ResourceManager.GetString("ExplicitMappingNameSettingIsRedundantTheSameNameXWillBeGeneratedAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is a part of Primary Key. It can&apos;t be changed..
        /// </summary>
        internal static string ExPrimaryKeyFieldCantBeChanged {
            get {
                return ResourceManager.GetString("ExPrimaryKeyFieldCantBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} must be declared in type &apos;{1}&apos;..
        /// </summary>
        internal static string ExPropertyXMustBeDeclaredInTypeY {
            get {
                return ResourceManager.GetString("ExPropertyXMustBeDeclaredInTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced field &apos;{0}&apos; and paired field are equal..
        /// </summary>
        internal static string ExReferencedFieldXAndPairedFieldAreEqual {
            get {
                return ResourceManager.GetString("ExReferencedFieldXAndPairedFieldAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not dervied from {1}..
        /// </summary>
        internal static string ExResultTypeIncorrect {
            get {
                return ResourceManager.GetString("ExResultTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;{0}&apos; is not found in application configuration file..
        /// </summary>
        internal static string ExSectionIsNotFoundInApplicationConfigurationFile {
            get {
                return ResourceManager.GetString("ExSectionIsNotFoundInApplicationConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with name &apos;{0}&apos; already exists in StorageInfo.Services collection..
        /// </summary>
        internal static string ExServiceWithNameAlreadyExistsInStorageInfoServicesCollection {
            get {
                return ResourceManager.GetString("ExServiceWithNameAlreadyExistsInStorageInfoServicesCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session bound object out of session scope..
        /// </summary>
        internal static string ExSessionBoundObjectOutOfSessionScope {
            get {
                return ResourceManager.GetString("ExSessionBoundObjectOutOfSessionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is already disposed..
        /// </summary>
        internal static string ExSessionIsAlreadyDisposed {
            get {
                return ResourceManager.GetString("ExSessionIsAlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is not open. You can perform this operation inside &apos;using (domain.OpenSession()) { ... }&apos; block..
        /// </summary>
        internal static string ExSessionIsNotOpen {
            get {
                return ResourceManager.GetString("ExSessionIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session with name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ExSessionWithNameXAlreadyExists {
            get {
                return ResourceManager.GetString("ExSessionWithNameXAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified values aren&apos;t enough to create key for type {0}.
        /// </summary>
        internal static string ExSpecifiedValuesArentEnoughToCreateKeyForTypeX {
            get {
                return ResourceManager.GetString("ExSpecifiedValuesArentEnoughToCreateKeyForTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateTransaction property value differs from the current transaction..
        /// </summary>
        internal static string ExStateTransactionIsDifferent {
            get {
                return ResourceManager.GetString("ExStateTransactionIsDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler provider not found for &quot;{0}&quot; connection type. Search folder &quot;{1}&quot;..
        /// </summary>
        internal static string ExStorageProviderNotFound {
            get {
                return ResourceManager.GetString("ExStorageProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures do not support fields of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExStructuresDoNotSupportFieldsOfTypeX {
            get {
                return ResourceManager.GetString("ExStructuresDoNotSupportFieldsOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no suitable types in &quot;{0}&quot;..
        /// </summary>
        internal static string ExThereAreNoSuitableTypes {
            get {
                return ResourceManager.GetString("ExThereAreNoSuitableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process operation without transaction. Please create TransactionScope before..
        /// </summary>
        internal static string ExTransactionRequired {
            get {
                return ResourceManager.GetString("ExTransactionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type cannot be null.
        /// </summary>
        internal static string ExTypeCantBeNull {
            get {
                return ResourceManager.GetString("ExTypeCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeDef &apos;{0}&apos; is already belongs to hierarchy with the root = &apos;{1}&apos;..
        /// </summary>
        internal static string ExTypeDefXIsAlreadyBelongsToHierarchyWithTheRootY {
            get {
                return ResourceManager.GetString("ExTypeDefXIsAlreadyBelongsToHierarchyWithTheRootY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeId for type &apos;{0}&apos; is not found..
        /// </summary>
        internal static string ExTypeIdForTypeXIsNotFound {
            get {
                return ResourceManager.GetString("ExTypeIdForTypeXIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeInfo hierarchy does not correspond to provided hierarchy..
        /// </summary>
        internal static string ExTypeInfoHierarchyMistmatch {
            get {
                return ResourceManager.GetString("ExTypeInfoHierarchyMistmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type specified..
        /// </summary>
        internal static string ExTypeMustBeEntityDescendant {
            get {
                return ResourceManager.GetString("ExTypeMustBeEntityDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} not found in model..
        /// </summary>
        internal static string ExTypeNotFoundInModel {
            get {
                return ResourceManager.GetString("ExTypeNotFoundInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type with name &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string ExTypeWithNameXIsAlreadyDefined {
            get {
                return ResourceManager.GetString("ExTypeWithNameXIsAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type with name &quot;{0}&quot; is not found in metadata..
        /// </summary>
        internal static string ExTypeWithNameXIsNotFoundInMetadata {
            get {
                return ResourceManager.GetString("ExTypeWithNameXIsNotFoundInMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type with type id &apos;{0}&apos; is not found..
        /// </summary>
        internal static string ExTypeWithTypeIdXIsNotFound {
            get {
                return ResourceManager.GetString("ExTypeWithTypeIdXIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not implement &apos;{1}&apos; interface..
        /// </summary>
        internal static string ExTypeXDoesNotImplementYInterface {
            get {
                return ResourceManager.GetString("ExTypeXDoesNotImplementYInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string ExTypeXIsAlreadyDefined {
            get {
                return ResourceManager.GetString("ExTypeXIsAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not collatable..
        /// </summary>
        internal static string ExTypeXIsNotCollatable {
            get {
                return ResourceManager.GetString("ExTypeXIsNotCollatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not registered in the model..
        /// </summary>
        internal static string ExTypeXIsNotRegisteredInTheModel {
            get {
                return ResourceManager.GetString("ExTypeXIsNotRegisteredInTheModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ExTypeXIsNotSupported {
            get {
                return ResourceManager.GetString("ExTypeXIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have public instance parameterless constructor in order to be used as storage definition builder..
        /// </summary>
        internal static string ExTypeXMustHavePublicInstanceParameterlessConstructorInOrderToBeUsedAsStorageDefinitionBuilder {
            get {
                return ResourceManager.GetString("ExTypeXMustHavePublicInstanceParameterlessConstructorInOrderToBeUsedAsStorageDefi" +
                        "nitionBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; was not registered for activation..
        /// </summary>
        internal static string ExTypeXWasNotRegisteredForActivation {
            get {
                return ResourceManager.GetString("ExTypeXWasNotRegisteredForActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to activate EntitySet for &apos;{0}&apos; field because it does not has association..
        /// </summary>
        internal static string ExUnableToActivateEntitySetWithoutAssociation {
            get {
                return ResourceManager.GetString("ExUnableToActivateEntitySetWithoutAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to clone system session configuration..
        /// </summary>
        internal static string ExUnableToCloneSystemSessionConfiguration {
            get {
                return ResourceManager.GetString("ExUnableToCloneSystemSessionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create key for &apos;{0}&apos; hierarchy. Key value or key generator should be specified..
        /// </summary>
        internal static string ExUnableToCreateKeyForXHierarchy {
            get {
                return ResourceManager.GetString("ExUnableToCreateKeyForXHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify deleted object..
        /// </summary>
        internal static string ExUnableToModifyDeletedObject {
            get {
                return ResourceManager.GetString("ExUnableToModifyDeletedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve type for Key &apos;{0}&apos;..
        /// </summary>
        internal static string ExUnableToResolveTypeForKeyX {
            get {
                return ResourceManager.GetString("ExUnableToResolveTypeForKeyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set key field &apos;{0}&apos; explicitly..
        /// </summary>
        internal static string ExUnableToSetKeyFieldXExplicitly {
            get {
                return ResourceManager.GetString("ExUnableToSetKeyFieldXExplicitly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown entity serialization kind &apos;{0}&apos;..
        /// </summary>
        internal static string ExUnknownEntitySerializationKindX {
            get {
                return ResourceManager.GetString("ExUnknownEntitySerializationKindX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown expression type: &apos;{0} ({1})&apos;.
        /// </summary>
        internal static string ExUnknownExpressionType {
            get {
                return ResourceManager.GetString("ExUnknownExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported expression type: {0}.
        /// </summary>
        internal static string ExUnsupportedExpressionType {
            get {
                return ResourceManager.GetString("ExUnsupportedExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported field type: &apos;{0}&apos;.
        /// </summary>
        internal static string ExUnsupportedFieldTypeX {
            get {
                return ResourceManager.GetString("ExUnsupportedFieldTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type: {0}..
        /// </summary>
        internal static string ExUnsupportedType {
            get {
                return ResourceManager.GetString("ExUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade of assembly &quot;{0}&quot; from version {1} to {2} is not supported..
        /// </summary>
        internal static string ExUpgradeOfAssemblyXFromVersionYToZIsNotSupported {
            get {
                return ResourceManager.GetString("ExUpgradeOfAssemblyXFromVersionYToZIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be &apos;{0}&apos; descendant..
        /// </summary>
        internal static string ExValueShouldBeXDescendant {
            get {
                return ResourceManager.GetString("ExValueShouldBeXDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong key structure..
        /// </summary>
        internal static string ExWrongKeyStructure {
            get {
                return ResourceManager.GetString("ExWrongKeyStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong persistent type candidate: &apos;{0}&apos;..
        /// </summary>
        internal static string ExWrongPersistentTypeCandidate {
            get {
                return ResourceManager.GetString("ExWrongPersistentTypeCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; descendant is already a root of another hierarchy..
        /// </summary>
        internal static string ExXDescendantIsAlreadyARootOfAnotherHierarchy {
            get {
                return ResourceManager.GetString("ExXDescendantIsAlreadyARootOfAnotherHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generators.
        /// </summary>
        internal static string Generators {
            get {
                return ResourceManager.GetString("Generators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy columns.
        /// </summary>
        internal static string HierarchyColumns {
            get {
                return ResourceManager.GetString("HierarchyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes.
        /// </summary>
        internal static string Indexes {
            get {
                return ResourceManager.GetString("Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building {0}.
        /// </summary>
        internal static string LogBuildingX {
            get {
                return ResourceManager.GetString("LogBuildingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing comparison result:
        ///{0}.
        /// </summary>
        internal static string LogClearingComparisonResultX {
            get {
                return ResourceManager.GetString("LogClearingComparisonResultX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison result:
        ///{0}.
        /// </summary>
        internal static string LogComparisonResultX {
            get {
                return ResourceManager.GetString("LogComparisonResultX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0}.
        /// </summary>
        internal static string LogCreatingX {
            get {
                return ResourceManager.GetString("LogCreatingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defining &apos;{0}&apos;.
        /// </summary>
        internal static string LogDefiningX {
            get {
                return ResourceManager.GetString("LogDefiningX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted schema:.
        /// </summary>
        internal static string LogExtractedSchema {
            get {
                return ResourceManager.GetString("LogExtractedSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.Assembly created: {0}.
        /// </summary>
        internal static string LogMetadataAssemblyCreatedX {
            get {
                return ResourceManager.GetString("LogMetadataAssemblyCreatedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.Assembly updated: {0}, from version {1} to {2}.
        /// </summary>
        internal static string LogMetadataAssemblyUpdatedXFromVersionYToZ {
            get {
                return ResourceManager.GetString("LogMetadataAssemblyUpdatedXFromVersionYToZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.Type renamed: &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string LogMetadataTypeRenamedXToY {
            get {
                return ResourceManager.GetString("LogMetadataTypeRenamedXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionBound method &apos;{0} &apos;of type &apos;{1}&apos;.
        /// </summary>
        internal static string LogSessionBoundMethodXOfTypeY {
            get {
                return ResourceManager.GetString("LogSessionBoundMethodXOfTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing schema in {0} mode.
        /// </summary>
        internal static string LogSynchronizingSchemaInXMode {
            get {
                return ResourceManager.GetString("LogSynchronizingSchemaInXMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target schema:.
        /// </summary>
        internal static string LogTargetSchema {
            get {
                return ResourceManager.GetString("LogTargetSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating {0}.
        /// </summary>
        internal static string LogValidatingX {
            get {
                return ResourceManager.GetString("LogValidatingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Version={1}).
        /// </summary>
        internal static string MetadataAssemblyFormat {
            get {
                return ResourceManager.GetString("MetadataAssemblyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Id={1}).
        /// </summary>
        internal static string MetadataTypeFormat {
            get {
                return ResourceManager.GetString("MetadataTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Definition.
        /// </summary>
        internal static string ModelDefinition {
            get {
                return ResourceManager.GetString("ModelDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}
        ///Hints:
        ///{1}
        ///Difference:
        ///{2}
        ///Actions:
        ///{3}.
        /// </summary>
        internal static string SchemaComparisonResultFormat {
            get {
                return ResourceManager.GetString("SchemaComparisonResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system types.
        /// </summary>
        internal static string SystemTypes {
            get {
                return ResourceManager.GetString("SystemTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not implement &apos;{1}.{2} field.&apos;.
        /// </summary>
        internal static string TypeXDoesNotImplementYZField {
            get {
                return ResourceManager.GetString("TypeXDoesNotImplementYZField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not an &apos;{1}&apos; descendant..
        /// </summary>
        internal static string TypeXIsNotAnYDescendant {
            get {
                return ResourceManager.GetString("TypeXIsNotAnYDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be less then {0}..
        /// </summary>
        internal static string ValueCanNotBeLessThenX {
            get {
                return ResourceManager.GetString("ValueCanNotBeLessThenX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be null..
        /// </summary>
        internal static string ValueCanNotBeNull {
            get {
                return ResourceManager.GetString("ValueCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be an entity that is already removed..
        /// </summary>
        internal static string ValueCanNotBeRemovedEntity {
            get {
                return ResourceManager.GetString("ValueCanNotBeRemovedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not exceed {0}..
        /// </summary>
        internal static string ValueLengthCanNotExceedX {
            get {
                return ResourceManager.GetString("ValueLengthCanNotExceedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should match regex pattern &apos;{0}&apos;.
        /// </summary>
        internal static string ValueShouldMatchRegexPatternX {
            get {
                return ResourceManager.GetString("ValueShouldMatchRegexPatternX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type mismatch for field &apos;{0}&apos;.
        /// </summary>
        internal static string ValueTypeMismatchForFieldX {
            get {
                return ResourceManager.GetString("ValueTypeMismatchForFieldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not applicable to &apos;{1}&apos; descendants..
        /// </summary>
        internal static string XIsNotApplicableToYDescendants {
            get {
                return ResourceManager.GetString("XIsNotApplicableToYDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        internal static string ZeroAssemblyVersion {
            get {
                return ResourceManager.GetString("ZeroAssemblyVersion", resourceCulture);
            }
        }
    }
}
