//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtensive.Storage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtensive.Storage.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string AspectDebugMessage {
            get {
                return ResourceManager.GetString("AspectDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: multiple attributes of type &apos;{1}&apos; are not allowed here..
        /// </summary>
        internal static string AspectExMultipleAttributesOfTypeXAreNotAllowedHere {
            get {
                return ResourceManager.GetString("AspectExMultipleAttributesOfTypeXAreNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value length {0} greater than column Length {1}. .
        /// </summary>
        internal static string ExColumnLength {
            get {
                return ResourceManager.GetString("ExColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assign null to not-nullable column..
        /// </summary>
        internal static string ExColumnNotNullable {
            get {
                return ResourceManager.GetString("ExColumnNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; is not found..
        /// </summary>
        internal static string ExColumnXIsNotFound {
            get {
                return ResourceManager.GetString("ExColumnXIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer for type &apos;{0}&apos; is not available..
        /// </summary>
        internal static string ExComparerForTypeIsNotAvailable {
            get {
                return ResourceManager.GetString("ExComparerForTypeIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint violation: constraint {0} on field &apos;{1}.{2}&apos; of object &apos;{3}&apos; failed on value {4}..
        /// </summary>
        internal static string ExConstraintViolation {
            get {
                return ResourceManager.GetString("ExConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load types from assembly {0}..
        /// </summary>
        internal static string ExCouldNotLoadTypesFromAssembly {
            get {
                return ResourceManager.GetString("ExCouldNotLoadTypesFromAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element with name &apos;{0}&apos; is contained in this instance already..
        /// </summary>
        internal static string ExElementWithNameContainedInThisInstanceAlready {
            get {
                return ResourceManager.GetString("ExElementWithNameContainedInThisInstanceAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element with type {0} is contained in this instance already..
        /// </summary>
        internal static string ExElementWithTypeIsContainedInThisInstanceAlready {
            get {
                return ResourceManager.GetString("ExElementWithTypeIsContainedInThisInstanceAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity is removed..
        /// </summary>
        internal static string ExEntityIsRemoved {
            get {
                return ResourceManager.GetString("ExEntityIsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify removed entity..
        /// </summary>
        internal static string ExEntityRemoved {
            get {
                return ResourceManager.GetString("ExEntityRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors have been occurred during storage build. See error log for details..
        /// </summary>
        internal static string ExErrorsDuringStorageBuild {
            get {
                return ResourceManager.GetString("ExErrorsDuringStorageBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} not found in model..
        /// </summary>
        internal static string ExFieldNotFoundInModel {
            get {
                return ResourceManager.GetString("ExFieldNotFoundInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with name &apos;{0}&apos; already exists in Entity.Fields collection..
        /// </summary>
        internal static string ExFieldWithNameAlreadyExistsInEntityFieldsCollection {
            get {
                return ResourceManager.GetString("ExFieldWithNameAlreadyExistsInEntityFieldsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} has &apos;{1}&apos; type but is marked as not nullable..
        /// </summary>
        internal static string ExFieldXHasYTypeButIsMarkedAsNotNullable {
            get {
                return ResourceManager.GetString("ExFieldXHasYTypeButIsMarkedAsNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index already contains field &apos;{0}&apos;..
        /// </summary>
        internal static string ExIndexAlreadyContainsField {
            get {
                return ResourceManager.GetString("ExIndexAlreadyContainsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index field &apos;{0}&apos; is incorrect..
        /// </summary>
        internal static string ExIndexFieldXIsIncorrect {
            get {
                return ResourceManager.GetString("ExIndexFieldXIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must contain at least one field..
        /// </summary>
        internal static string ExIndexMustContainAtLeastOneField {
            get {
                return ResourceManager.GetString("ExIndexMustContainAtLeastOneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index with name &apos;{0}&apos; already exists in EntityInfo.Indexes collection..
        /// </summary>
        internal static string ExIndexWithNameAlreadyExistsInEntityInfoIndexesCollection {
            get {
                return ResourceManager.GetString("ExIndexWithNameAlreadyExistsInEntityInfoIndexesCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fill factor &apos;{0}&apos;. Value must be between 0 and 1..
        /// </summary>
        internal static string ExInvalidFillFactorXValueMustBeBetween0And1 {
            get {
                return ResourceManager.GetString("ExInvalidFillFactorXValueMustBeBetween0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create key. Key params do not correspond to key structure..
        /// </summary>
        internal static string ExInvalidKeyParams {
            get {
                return ResourceManager.GetString("ExInvalidKeyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;Length&apos; attribute on &apos;{0}&apos; field..
        /// </summary>
        internal static string ExInvalidLengthAttributeOnXField {
            get {
                return ResourceManager.GetString("ExInvalidLengthAttributeOnXField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key field &apos;{0}&apos; was not found in type &apos;{1}&apos;..
        /// </summary>
        internal static string ExKeyFieldXWasNotFoundInTypeY {
            get {
                return ResourceManager.GetString("ExKeyFieldXWasNotFoundInTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key provider &apos;{0}&apos; and hierarchy {1} key field amount mismatch..
        /// </summary>
        internal static string ExKeyProviderXAndHierarchyYKeyFieldAmountMismatch {
            get {
                return ResourceManager.GetString("ExKeyProviderXAndHierarchyYKeyFieldAmountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key provider &apos;{0}&apos; should define at least one key field..
        /// </summary>
        internal static string ExKeyProviderXShouldDefineAtLeastOneKeyField {
            get {
                return ResourceManager.GetString("ExKeyProviderXShouldDefineAtLeastOneKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; was not found in storage..
        /// </summary>
        internal static string ExKeyXWasNotFoundInStorage {
            get {
                return ResourceManager.GetString("ExKeyXWasNotFoundInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object outside of initial transaction scope..
        /// </summary>
        internal static string ExOutOfTransactionScope {
            get {
                return ResourceManager.GetString("ExOutOfTransactionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired field &apos;{0}&apos; was not found in &apos;{1}&apos; type..
        /// </summary>
        internal static string ExPairedFieldXWasNotFoundInYType {
            get {
                return ResourceManager.GetString("ExPairedFieldXWasNotFoundInYType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;PairTo&apos; attribute can not be used with &apos;{0}&apos; field..
        /// </summary>
        internal static string ExPairToAttributeCanNotBeUsedWithXField {
            get {
                return ResourceManager.GetString("ExPairToAttributeCanNotBeUsedWithXField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit &apos;IsNullable&apos; attribute is redundant.
        /// </summary>
        internal static string ExplicitIsNullableAttributeIsRedundant {
            get {
                return ResourceManager.GetString("ExplicitIsNullableAttributeIsRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit &apos;LazyLoad&apos; attribute on field &apos;{0}&apos; is redundant.
        /// </summary>
        internal static string ExplicitLazyLoadAttributeOnFieldXIsRedundant {
            get {
                return ResourceManager.GetString("ExplicitLazyLoadAttributeOnFieldXIsRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit mapping name setting is redundant. The same name &apos;{0}&apos; will be generated automatically..
        /// </summary>
        internal static string ExplicitMappingNameSettingIsRedundantTheSameNameXWillBeGeneratedAutomatically {
            get {
                return ResourceManager.GetString("ExplicitMappingNameSettingIsRedundantTheSameNameXWillBeGeneratedAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is a part of Primary Key. It can&apos;t be changed..
        /// </summary>
        internal static string ExPrimaryKeyFieldCantBeChanged {
            get {
                return ResourceManager.GetString("ExPrimaryKeyFieldCantBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} must be declared in type &apos;{1}&apos;..
        /// </summary>
        internal static string ExPropertyXMustBeDeclaredInTypeY {
            get {
                return ResourceManager.GetString("ExPropertyXMustBeDeclaredInTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not dervied from {1}..
        /// </summary>
        internal static string ExResultTypeIncorrect {
            get {
                return ResourceManager.GetString("ExResultTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with name &apos;{0}&apos; already exists in StorageInfo.Services collection..
        /// </summary>
        internal static string ExServiceWithNameAlreadyExistsInStorageInfoServicesCollection {
            get {
                return ResourceManager.GetString("ExServiceWithNameAlreadyExistsInStorageInfoServicesCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session bound object out of session scope..
        /// </summary>
        internal static string ExSessionBoundObjectOutOfSessionScope {
            get {
                return ResourceManager.GetString("ExSessionBoundObjectOutOfSessionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler provider not found for &quot;{0}&quot; connection type. Search folder &quot;{1}&quot;..
        /// </summary>
        internal static string ExStorageProviderNotFound {
            get {
                return ResourceManager.GetString("ExStorageProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no suitable types in &quot;{0}&quot;..
        /// </summary>
        internal static string ExThereAreNoSuitableTypes {
            get {
                return ResourceManager.GetString("ExThereAreNoSuitableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process operation without transaction. Please create TransactionScope before..
        /// </summary>
        internal static string ExTransactionRequired {
            get {
                return ResourceManager.GetString("ExTransactionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type cannot be null.
        /// </summary>
        internal static string ExTypeCantBeNull {
            get {
                return ResourceManager.GetString("ExTypeCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeDef &apos;{0}&apos; is already belongs to hierarchy with the root = &apos;{1}&apos;..
        /// </summary>
        internal static string ExTypeDefXIsAlreadyBelongsToHierarchyWithTheRootY {
            get {
                return ResourceManager.GetString("ExTypeDefXIsAlreadyBelongsToHierarchyWithTheRootY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeInfo hierarchy does not correspond to provided hierarchy..
        /// </summary>
        internal static string ExTypeInfoHierarchyMistmatch {
            get {
                return ResourceManager.GetString("ExTypeInfoHierarchyMistmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type specified..
        /// </summary>
        internal static string ExTypeMustBeEntityDescendant {
            get {
                return ResourceManager.GetString("ExTypeMustBeEntityDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} not found in model..
        /// </summary>
        internal static string ExTypeNotFoundInModel {
            get {
                return ResourceManager.GetString("ExTypeNotFoundInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not implement &apos;{1}&apos; interface..
        /// </summary>
        internal static string ExTypeXDoesNotImplementYInterface {
            get {
                return ResourceManager.GetString("ExTypeXDoesNotImplementYInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not collatable..
        /// </summary>
        internal static string ExTypeXIsNotCollatable {
            get {
                return ResourceManager.GetString("ExTypeXIsNotCollatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not registered in the model..
        /// </summary>
        internal static string ExTypeXIsNotRegisteredInTheModel {
            get {
                return ResourceManager.GetString("ExTypeXIsNotRegisteredInTheModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have public instance parameterless constructor in order to be used as storage definition builder..
        /// </summary>
        internal static string ExTypeXMustHavePublicInstanceParameterlessConstructorInOrderToBeUsedAsStorageDefinitionBuilder {
            get {
                return ResourceManager.GetString("ExTypeXMustHavePublicInstanceParameterlessConstructorInOrderToBeUsedAsStorageDefi" +
                        "nitionBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify deleted object..
        /// </summary>
        internal static string ExUnableToModifyDeletedObject {
            get {
                return ResourceManager.GetString("ExUnableToModifyDeletedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify key column..
        /// </summary>
        internal static string ExUnableToModifyKeyColumn {
            get {
                return ResourceManager.GetString("ExUnableToModifyKeyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type: {0}..
        /// </summary>
        internal static string ExUnsupportedType {
            get {
                return ResourceManager.GetString("ExUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; descendant is already a root of another hierarchy..
        /// </summary>
        internal static string ExXDescendantIsAlreadyARootOfAnotherHierarchy {
            get {
                return ResourceManager.GetString("ExXDescendantIsAlreadyARootOfAnotherHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with name &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string FieldWithNameXIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("FieldWithNameXIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; can&apos;t be load on demand as it is included in primary key..
        /// </summary>
        internal static string FieldXCanTBeLoadOnDemandAsItIsIncludedInPrimaryKey {
            get {
                return ResourceManager.GetString("FieldXCanTBeLoadOnDemandAsItIsIncludedInPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is already defined in type {1} or its ancestor..
        /// </summary>
        internal static string FieldXIsAlreadyDefinedInTypeXOrItsAncestor {
            get {
                return ResourceManager.GetString("FieldXIsAlreadyDefinedInTypeXOrItsAncestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexed properties are not supported..
        /// </summary>
        internal static string IndexedPropertiesAreNotSupported {
            get {
                return ResourceManager.GetString("IndexedPropertiesAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string IndexNameXIsInvalid {
            get {
                return ResourceManager.GetString("IndexNameXIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index with name &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string IndexWithNameXIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("IndexWithNameXIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface &apos;{0}&apos; does not belong to &apos;{1}&apos; hierarchy..
        /// </summary>
        internal static string InterfaceXDoesNotBelongToXHierarchy {
            get {
                return ResourceManager.GetString("InterfaceXDoesNotBelongToXHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field value, constraint {0} is violated..
        /// </summary>
        internal static string InvalidFieldValueConstraintXIsViolated {
            get {
                return ResourceManager.GetString("InvalidFieldValueConstraintXIsViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mapping name &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidMappingNameX {
            get {
                return ResourceManager.GetString("InvalidMappingNameX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;OnDelete&apos; attribute usage on field &apos;{0}&apos;. Field is not entity reference..
        /// </summary>
        internal static string InvalidOnDeleteAttributeUsageOnFieldXFieldIsNotEntityReference {
            get {
                return ResourceManager.GetString("InvalidOnDeleteAttributeUsageOnFieldXFieldIsNotEntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Session of specified ISessionBound object is invalid..
        /// </summary>
        internal static string InvalidSession {
            get {
                return ResourceManager.GetString("InvalidSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building handler provider..
        /// </summary>
        internal static string LogBuildingHandlerProvider {
            get {
                return ResourceManager.GetString("LogBuildingHandlerProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building key providers..
        /// </summary>
        internal static string LogBuildingKeyProviders {
            get {
                return ResourceManager.GetString("LogBuildingKeyProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building value converters..
        /// </summary>
        internal static string LogBuildingValueConverters {
            get {
                return ResourceManager.GetString("LogBuildingValueConverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionBound method &apos;{0} &apos;of type &apos;{1}&apos;.
        /// </summary>
        internal static string LogSessionBoundMethodXOfTypeY {
            get {
                return ResourceManager.GetString("LogSessionBoundMethodXOfTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating configuration..
        /// </summary>
        internal static string LogValidatingConfiguration {
            get {
                return ResourceManager.GetString("LogValidatingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {0} is invalid..
        /// </summary>
        internal static string NameXIsInvalid {
            get {
                return ResourceManager.GetString("NameXIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired field &apos;{0}&apos; has insufficient type. It should be reference to Entity or a EntitySet..
        /// </summary>
        internal static string PairedFieldXHasInsufficientTypeItShouldBeReferenceToEntityOrAEntitySet {
            get {
                return ResourceManager.GetString("PairedFieldXHasInsufficientTypeItShouldBeReferenceToEntityOrAEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced field &apos;{0}&apos; and paired field are equal..
        /// </summary>
        internal static string ReferencedFieldXAndPairedFieldAreEqual {
            get {
                return ResourceManager.GetString("ReferencedFieldXAndPairedFieldAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type with name &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string TypeWithNameXIsAlreadyDefined {
            get {
                return ResourceManager.GetString("TypeWithNameXIsAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not implement &apos;{1}.{2} field.&apos;.
        /// </summary>
        internal static string TypeXDoesNotImplementYZField {
            get {
                return ResourceManager.GetString("TypeXDoesNotImplementYZField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string TypeXIsAlreadyDefined {
            get {
                return ResourceManager.GetString("TypeXIsAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; was not registered for activation.
        /// </summary>
        internal static string TypeXWasNotRegisteredForActivation {
            get {
                return ResourceManager.GetString("TypeXWasNotRegisteredForActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported field type: &apos;{0}&apos;.
        /// </summary>
        internal static string UnsupportedFieldTypeX {
            get {
                return ResourceManager.GetString("UnsupportedFieldTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be less then {0}..
        /// </summary>
        internal static string ValueCanNotBeLessThenX {
            get {
                return ResourceManager.GetString("ValueCanNotBeLessThenX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be null..
        /// </summary>
        internal static string ValueCanNotBeNull {
            get {
                return ResourceManager.GetString("ValueCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be an entity that is already removed..
        /// </summary>
        internal static string ValueCanNotBeRemovedEntity {
            get {
                return ResourceManager.GetString("ValueCanNotBeRemovedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not exceed {0}..
        /// </summary>
        internal static string ValueLengthCanNotExceedX {
            get {
                return ResourceManager.GetString("ValueLengthCanNotExceedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should match regex pattern &apos;{0}&apos;.
        /// </summary>
        internal static string ValueShouldMatchRegexPatternX {
            get {
                return ResourceManager.GetString("ValueShouldMatchRegexPatternX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type mismatch for field &apos;{0}&apos;.
        /// </summary>
        internal static string ValueTypeMismatchForFieldX {
            get {
                return ResourceManager.GetString("ValueTypeMismatchForFieldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not applicable to &apos;{1}&apos; descendants..
        /// </summary>
        internal static string XIsNotApplicableToYDescendants {
            get {
                return ResourceManager.GetString("XIsNotApplicableToYDescendants", resourceCulture);
            }
        }
    }
}
