//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtensive.Storage.Providers.Sql.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtensive.Storage.Providers.Sql.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration is already finished..
        /// </summary>
        internal static string ExEnumerationIsAlreadyFinished {
            get {
                return ResourceManager.GetString("ExEnumerationIsAlreadyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration is not started..
        /// </summary>
        internal static string ExEnumerationIsNotStarted {
            get {
                return ResourceManager.GetString("ExEnumerationIsNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index {0} changed..
        /// </summary>
        internal static string ExIndexXXXChanged {
            get {
                return ResourceManager.GetString("ExIndexXXXChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert instance of type {0} with specified key. Query affected {1} tables, but expecrted {2} tables..
        /// </summary>
        internal static string ExInsertInvalid {
            get {
                return ResourceManager.GetString("ExInsertInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type {0} with specified key found several times in storage..
        /// </summary>
        internal static string ExInstanceMultipleResults {
            get {
                return ResourceManager.GetString("ExInstanceMultipleResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type {0} with specified key not found in storage..
        /// </summary>
        internal static string ExInstanceNotFound {
            get {
                return ResourceManager.GetString("ExInstanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified query returns multiple results..
        /// </summary>
        internal static string ExQueryMultipleResults {
            get {
                return ResourceManager.GetString("ExQueryMultipleResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader is not in consistent state..
        /// </summary>
        internal static string ExReaderIsNotInConsistentState {
            get {
                return ResourceManager.GetString("ExReaderIsNotInConsistentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} doesn&apos;t have primary index. Or index not found in storage..
        /// </summary>
        internal static string ExTypeDoesntHavePrimaryIndex {
            get {
                return ResourceManager.GetString("ExTypeDoesntHavePrimaryIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create connection. Check if all needed assemblies are present..
        /// </summary>
        internal static string ExUnableToCreateConnection {
            get {
                return ResourceManager.GetString("ExUnableToCreateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supported by current storage..
        /// </summary>
        internal static string ExUnsupportedColumnType {
            get {
                return ResourceManager.GetString("ExUnsupportedColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index {0} with attributes {1} is not supported..
        /// </summary>
        internal static string ExUnsupportedIndex {
            get {
                return ResourceManager.GetString("ExUnsupportedIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update instance of type {0} with specified key. Query affected {1} tables, but expecrted {2} tables..
        /// </summary>
        internal static string ExUpdateInvalid {
            get {
                return ResourceManager.GetString("ExUpdateInvalid", resourceCulture);
            }
        }
    }
}
