//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtensive.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtensive.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual target model.
        /// </summary>
        internal static string ActualTargetModel {
            get {
                return ResourceManager.GetString("ActualTargetModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string AnyCulture {
            get {
                return ResourceManager.GetString("AnyCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box({0}).
        /// </summary>
        internal static string BoxFormat {
            get {
                return ResourceManager.GetString("BoxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached({0}).
        /// </summary>
        internal static string CachedFormat {
            get {
                return ResourceManager.GetString("CachedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparisonRule({0}, {1}).
        /// </summary>
        internal static string ComparisonRuleFormat {
            get {
                return ResourceManager.GetString("ComparisonRuleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparisonRules({0}, [{1}]).
        /// </summary>
        internal static string ComparisonRulesFormat {
            get {
                return ResourceManager.GetString("ComparisonRulesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,6:F2}s @{1,-5} {2,5} {3,-24} {4}{5}.
        /// </summary>
        internal static string ComprehensiveLogFormat {
            get {
                return ResourceManager.GetString("ComprehensiveLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        internal static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{1}&quot; != &quot;{2}&quot; ({0}): {3}.
        /// </summary>
        internal static string DifferenceFormat {
            get {
                return ResourceManager.GetString("DifferenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}: .
        /// </summary>
        internal static string DifferencePropertyNamePrefix {
            get {
                return ResourceManager.GetString("DifferencePropertyNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&apos;.
        /// </summary>
        internal static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire({0}).
        /// </summary>
        internal static string EntireFormat {
            get {
                return ResourceManager.GetString("EntireFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accessed member is not a property..
        /// </summary>
        internal static string ExAccessedMemberIsNotProperty {
            get {
                return ResourceManager.GetString("ExAccessedMemberIsNotProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual conjunction operand count greater than MaxConjunctionOperandCount..
        /// </summary>
        internal static string ExActualConjunctionOperandCountGreaterThanExpected {
            get {
                return ResourceManager.GetString("ExActualConjunctionOperandCountGreaterThanExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is already disposed..
        /// </summary>
        internal static string ExAlreadyDisposed {
            get {
                return ResourceManager.GetString("ExAlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance is already initialized..
        /// </summary>
        internal static string ExAlreadyInitialized {
            get {
                return ResourceManager.GetString("ExAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can&apos;t be an empty string..
        /// </summary>
        internal static string ExArgumentCannotBeEmptyString {
            get {
                return ResourceManager.GetString("ExArgumentCannotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be greater than &apos;{0}&apos;.
        /// </summary>
        internal static string ExArgumentMustBeGreaterThanX {
            get {
                return ResourceManager.GetString("ExArgumentMustBeGreaterThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be greater that or equal &apos;{0}&apos;.
        /// </summary>
        internal static string ExArgumentMustBeGreaterThatOrEqualX {
            get {
                return ResourceManager.GetString("ExArgumentMustBeGreaterThatOrEqualX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be less than or equal &apos;{0}&apos;.
        /// </summary>
        internal static string ExArgumentMustBeLessThanOrEqualX {
            get {
                return ResourceManager.GetString("ExArgumentMustBeLessThanOrEqualX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be less than &apos;{0}&apos;.
        /// </summary>
        internal static string ExArgumentMustBeLessThanX {
            get {
                return ResourceManager.GetString("ExArgumentMustBeLessThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not be of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExArgumentMustnotBeOfTypeX {
            get {
                return ResourceManager.GetString("ExArgumentMustnotBeOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument should be in range [{0}...{1}]..
        /// </summary>
        internal static string ExArgumentShouldBeInRange {
            get {
                return ResourceManager.GetString("ExArgumentShouldBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument value must be greater than or equal to zero..
        /// </summary>
        internal static string ExArgumentValueMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("ExArgumentValueMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument value must be greater than zero..
        /// </summary>
        internal static string ExArgumentValueMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ExArgumentValueMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is less than the argument &apos;{1}&apos;..
        /// </summary>
        internal static string ExArgumentXIsLessThanArgumentY {
            get {
                return ResourceManager.GetString("ExArgumentXIsLessThanArgumentY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array does not have zero-based indexing..
        /// </summary>
        internal static string ExArrayDoesNotHaveZeroBasedIndexing {
            get {
                return ResourceManager.GetString("ExArrayDoesNotHaveZeroBasedIndexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array is multidimentional..
        /// </summary>
        internal static string ExArrayIsMultidimensional {
            get {
                return ResourceManager.GetString("ExArrayIsMultidimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of exceptions is caught..
        /// </summary>
        internal static string ExASetOfExceptionsIsCaught {
            get {
                return ResourceManager.GetString("ExASetOfExceptionsIsCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding has failed for {0}. Check property declaration..
        /// </summary>
        internal static string ExBindingFailedForX {
            get {
                return ResourceManager.GetString("ExBindingFailedForX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both measurements have no value..
        /// </summary>
        internal static string ExBothMeasurementsHaveNoValue {
            get {
                return ResourceManager.GetString("ExBothMeasurementsHaveNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Source and Target are null..
        /// </summary>
        internal static string ExBothSourceAndTargetAreNull {
            get {
                return ResourceManager.GetString("ExBothSourceAndTargetAreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t activate service &apos;{0}&apos;. Error: {1}.
        /// </summary>
        internal static string ExCannotActivateServiceXErrorY {
            get {
                return ResourceManager.GetString("ExCannotActivateServiceXErrorY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t activate service &apos;{0}&apos; with name &quot;{1}&quot;. Error: {2}.
        /// </summary>
        internal static string ExCannotActivateServiceXWithKeyYErrorZ {
            get {
                return ResourceManager.GetString("ExCannotActivateServiceXWithKeyYErrorZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find a constructor to execute {0}..
        /// </summary>
        internal static string ExCannotFindConstructorToExecuteX {
            get {
                return ResourceManager.GetString("ExCannotFindConstructorToExecuteX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse the call to the comparison method..
        /// </summary>
        internal static string ExCannotParseCallToComparisonMethod {
            get {
                return ResourceManager.GetString("ExCannotParseCallToComparisonMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create associates for generic type definitions (type &apos;{0}&apos;)..
        /// </summary>
        internal static string ExCantCreateAssociateForGenericTypeDefinitions {
            get {
                return ResourceManager.GetString("ExCantCreateAssociateForGenericTypeDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find associated {0} of type &apos;{1}&apos; for type &apos;{2}&apos;..
        /// </summary>
        internal static string ExCantFindAssociate {
            get {
                return ResourceManager.GetString("ExCantFindAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find associated {0} of type &apos;{1}&apos; for type &apos;{2}&apos; or &apos;{3}&apos;..
        /// </summary>
        internal static string ExCantFindAssociate2 {
            get {
                return ResourceManager.GetString("ExCantFindAssociate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfinityType.None can&apos;t be passed to this constructor..
        /// </summary>
        internal static string ExCantPassNoInfinityToThisConstructor {
            get {
                return ResourceManager.GetString("ExCantPassNoInfinityToThisConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection already contains item with the specified key..
        /// </summary>
        internal static string ExCollectionAlreadyContainsItemWithSpecifiedKey {
            get {
                return ResourceManager.GetString("ExCollectionAlreadyContainsItemWithSpecifiedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecton already contains specified item..
        /// </summary>
        internal static string ExCollectionAlreadyContainsSpecifiedItem {
            get {
                return ResourceManager.GetString("ExCollectionAlreadyContainsSpecifiedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection has been changed during the enumeration..
        /// </summary>
        internal static string ExCollectionHasBeenChanged {
            get {
                return ResourceManager.GetString("ExCollectionHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection has been modified..
        /// </summary>
        internal static string ExCollectionHasBeenModified {
            get {
                return ResourceManager.GetString("ExCollectionHasBeenModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is empty..
        /// </summary>
        internal static string ExCollectionIsEmpty {
            get {
                return ResourceManager.GetString("ExCollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is read-only..
        /// </summary>
        internal static string ExCollectionIsReadOnly {
            get {
                return ResourceManager.GetString("ExCollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item should be either an ICollection or ICountable..
        /// </summary>
        internal static string ExCollectionOrCoutableExcpected {
            get {
                return ResourceManager.GetString("ExCollectionOrCoutableExcpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection property {0} is bound to the property {1} that isn&apos;t collection..
        /// </summary>
        internal static string ExCollectionPropertyXIsBoundToPropertyYThatIsNotCollection {
            get {
                return ResourceManager.GetString("ExCollectionPropertyXIsBoundToPropertyYThatIsNotCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container type does not provide a suitable constructor..
        /// </summary>
        internal static string ExContainerTypeDoesNotProvideASuitableConstructor {
            get {
                return ResourceManager.GetString("ExContainerTypeDoesNotProvideASuitableConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container type must implement {0}..
        /// </summary>
        internal static string ExContainerTypeMustImplementX {
            get {
                return ResourceManager.GetString("ExContainerTypeMustImplementX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required. Use {1} to set it..
        /// </summary>
        internal static string ExContextRequired {
            get {
                return ResourceManager.GetString("ExContextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy a part of the stream to itself. Use StreamExtensions.Copy method instead..
        /// </summary>
        internal static string ExCopyToMustOperateWithDifferentStreams {
            get {
                return ResourceManager.GetString("ExCopyToMustOperateWithDifferentStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load types from the assembly &apos;{0}&apos;..
        /// </summary>
        internal static string ExCouldNotLoadTypesFromAssembly {
            get {
                return ResourceManager.GetString("ExCouldNotLoadTypesFromAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture of the applied rule should either be undefined (null), or be the same as on target rule..
        /// </summary>
        internal static string ExCultureOfAppliedRuleShouldBeEitherNullOrTheSameAsOnTarget {
            get {
                return ResourceManager.GetString("ExCultureOfAppliedRuleShouldBeEitherNullOrTheSameAsOnTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency operation with full name &quot;{0}&quot; is already registered..
        /// </summary>
        internal static string ExDependencyOperationIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("ExDependencyOperationIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor is in invalid state..
        /// </summary>
        internal static string ExDescriptorIsInInvalidState {
            get {
                return ResourceManager.GetString("ExDescriptorIsInInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization error: some SerializationData slots were not recognized, thus the format of the serialized data differs from the supported one..
        /// </summary>
        internal static string ExDeserializationErrorUnrecognizedSlotsAreFound {
            get {
                return ResourceManager.GetString("ExDeserializationErrorUnrecognizedSlotsAreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream length not enough to deserialize object of specified type..
        /// </summary>
        internal static string ExDeserializationStreamLengthIncorrect {
            get {
                return ResourceManager.GetString("ExDeserializationStreamLengthIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destionation array is too small..
        /// </summary>
        internal static string ExDestionationArrayIsTooSmall {
            get {
                return ResourceManager.GetString("ExDestionationArrayIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The detection of changes in user structure collection isn&apos;t supported..
        /// </summary>
        internal static string ExDetectionOfChangesInUserStructureCollectionIsNotSupported {
            get {
                return ResourceManager.GetString("ExDetectionOfChangesInUserStructureCollectionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference related to {0} type is not found on the UpgradeContext stack..
        /// </summary>
        internal static string ExDifferenceRelatedToXTypeIsNotFoundOnTheUpgradeContextStack {
            get {
                return ResourceManager.GetString("ExDifferenceRelatedToXTypeIsNotFoundOnTheUpgradeContextStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different TupleDescriptors are not valid here: {0} and {1}..
        /// </summary>
        internal static string ExDifferentTupleDescriptors {
            get {
                return ResourceManager.GetString("ExDifferentTupleDescriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndPoints order of both ranges must be equal..
        /// </summary>
        internal static string ExEndPointOrderMustBeEqual {
            get {
                return ResourceManager.GetString("ExEndPointOrderMustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration is already finished..
        /// </summary>
        internal static string ExEnumerationIsAlreadyFinished {
            get {
                return ResourceManager.GetString("ExEnumerationIsAlreadyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape character must differ from delimiter character..
        /// </summary>
        internal static string ExEscapeCharacterMustDifferFromDelimiterCharacter {
            get {
                return ResourceManager.GetString("ExEscapeCharacterMustDifferFromDelimiterCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception was thrown during the task&apos;s execution..
        /// </summary>
        internal static string ExExceptionWasThrownDuringTaskExecution {
            get {
                return ResourceManager.GetString("ExExceptionWasThrownDuringTaskExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected value of the parameter is already set..
        /// </summary>
        internal static string ExExpectedValueOfParameterIsAlreadySet {
            get {
                return ResourceManager.GetString("ExExpectedValueOfParameterIsAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; must reference field..
        /// </summary>
        internal static string ExExpression0MustReferenceField {
            get {
                return ResourceManager.GetString("ExExpression0MustReferenceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; must reference property..
        /// </summary>
        internal static string ExExpression0MustReferenceProperty {
            get {
                return ResourceManager.GetString("ExExpression0MustReferenceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression having the different normal form must not be a root expression..
        /// </summary>
        internal static string ExExpressionHavingDifferentNormalFormMustNotBeRoot {
            get {
                return ResourceManager.GetString("ExExpressionHavingDifferentNormalFormMustNotBeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression having the equal normal form must be a root expression..
        /// </summary>
        internal static string ExExpressionHavingEqualNormalFormMustBeRoot {
            get {
                return ResourceManager.GetString("ExExpressionHavingEqualNormalFormMustBeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression must return a value of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExExpressionMustReturnValueOfTypeX {
            get {
                return ResourceManager.GetString("ExExpressionMustReturnValueOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with index &apos;{0}&apos; is infinitу..
        /// </summary>
        internal static string ExFieldIsInfinite {
            get {
                return ResourceManager.GetString("ExFieldIsInfinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic parameter &apos;{0}&apos; should be of type &apos;{1}&apos;..
        /// </summary>
        internal static string ExGenericParameterShouldBeOfTypeT {
            get {
                return ResourceManager.GetString("ExGenericParameterShouldBeOfTypeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given key was not present in the dictionary..
        /// </summary>
        internal static string ExGivenKeyNotPresent {
            get {
                return ResourceManager.GetString("ExGivenKeyNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion from type {0} to type {1} is inadmissible..
        /// </summary>
        internal static string ExInadmissibleTypeConversion {
            get {
                return ResourceManager.GetString("ExInadmissibleTypeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible array type..
        /// </summary>
        internal static string ExIncompatibleArrayType {
            get {
                return ResourceManager.GetString("ExIncompatibleArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two collections cannot be combined because they use different comparison operations..
        /// </summary>
        internal static string ExInconsistentComparisons {
            get {
                return ResourceManager.GetString("ExInconsistentComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is out of range..
        /// </summary>
        internal static string ExIndexOutOfRange {
            get {
                return ResourceManager.GetString("ExIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index should be in [{0}...{1}] range..
        /// </summary>
        internal static string ExIndexShouldBeInNMRange {
            get {
                return ResourceManager.GetString("ExIndexShouldBeInNMRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance is locked..
        /// </summary>
        internal static string ExInstanceIsLocked {
            get {
                return ResourceManager.GetString("ExInstanceIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A instance must have non-null IHasSyncRoot.SyncRoot property value..
        /// </summary>
        internal static string ExInstanceMustHaveSyncRoot {
            get {
                return ResourceManager.GetString("ExInstanceMustHaveSyncRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: {0}.
        /// </summary>
        internal static string ExInternalError {
            get {
                return ResourceManager.GetString("ExInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active scope is invalid - it differs from the expected one. Probably you have forgot to dispose some nested scope..
        /// </summary>
        internal static string ExInvalidActiveScope {
            get {
                return ResourceManager.GetString("ExInvalidActiveScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AfterPath property value..
        /// </summary>
        internal static string ExInvalidAfterPathPropertyValue {
            get {
                return ResourceManager.GetString("ExInvalidAfterPathPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument type: expected type is {0}..
        /// </summary>
        internal static string ExInvalidArgumentType {
            get {
                return ResourceManager.GetString("ExInvalidArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified capacity value is less than collection count..
        /// </summary>
        internal static string ExInvalidCapacity {
            get {
                return ResourceManager.GetString("ExInvalidCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast from &apos;{0}&apos; to &apos;{1}&apos; is invalid..
        /// </summary>
        internal static string ExInvalidCast {
            get {
                return ResourceManager.GetString("ExInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid context activation sequence..
        /// </summary>
        internal static string ExInvalidContextActivationSequence {
            get {
                return ResourceManager.GetString("ExInvalidContextActivationSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid context deactivation sequence..
        /// </summary>
        internal static string ExInvalidContextDeactivationSequence {
            get {
                return ResourceManager.GetString("ExInvalidContextDeactivationSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field map size. Expected {0}..
        /// </summary>
        internal static string ExInvalidFieldMapSizeExpectedX {
            get {
                return ResourceManager.GetString("ExInvalidFieldMapSizeExpectedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; formatter process type is invalid for the current operation..
        /// </summary>
        internal static string ExInvalidFormatterProcessType {
            get {
                return ResourceManager.GetString("ExInvalidFormatterProcessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Nesting of node &quot;{0}&quot;..
        /// </summary>
        internal static string ExInvalidNestingOfNodeX {
            get {
                return ResourceManager.GetString("ExInvalidNestingOfNodeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid node state..
        /// </summary>
        internal static string ExInvalidNodeState {
            get {
                return ResourceManager.GetString("ExInvalidNodeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object serializer is invalid, since similar value serializer exists..
        /// </summary>
        internal static string ExInvalidObjectSerializerSimilarValueSerializerExists {
            get {
                return ResourceManager.GetString("ExInvalidObjectSerializerSimilarValueSerializerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parent value..
        /// </summary>
        internal static string ExInvalidParentValue {
            get {
                return ResourceManager.GetString("ExInvalidParentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with invalid (possibly - unspecified) type is found..
        /// </summary>
        internal static string ExInvalidRecordType {
            get {
                return ResourceManager.GetString("ExInvalidRecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can&apos;t be an IsReferable serializer, since it serializes IReference type..
        /// </summary>
        internal static string ExInvalidSerializerBehaviorMustNotBeReferable {
            get {
                return ResourceManager.GetString("ExInvalidSerializerBehaviorMustNotBeReferable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic parameter T is resolved to associated &apos;{0}&apos;, although &apos;{1}&apos; is expected..
        /// </summary>
        internal static string ExInvalidSerializerType {
            get {
                return ResourceManager.GetString("ExInvalidSerializerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction state (&apos;{0}&apos;). Expected state(s) is (are) &apos;{1}&apos;..
        /// </summary>
        internal static string ExInvalidTransactionState {
            get {
                return ResourceManager.GetString("ExInvalidTransactionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TupleDescriptor. Expected descriptor is {0}..
        /// </summary>
        internal static string ExInvalidTupleDescriptorExpectedDescriptorIs {
            get {
                return ResourceManager.GetString("ExInvalidTupleDescriptorExpectedDescriptorIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is invalid URL..
        /// </summary>
        internal static string ExInvalidUrl {
            get {
                return ResourceManager.GetString("ExInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists..
        /// </summary>
        internal static string ExItemAlreadyExists {
            get {
                return ResourceManager.GetString("ExItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified item cannot be cached because its type is incompatible with underlying storage format..
        /// </summary>
        internal static string ExItemCantBeCachedIncompatibleType {
            get {
                return ResourceManager.GetString("ExItemCantBeCachedIncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified item cannot be cached because its type is incompatible with ITuple..
        /// </summary>
        internal static string ExItemCantBeComparedIncompatibleType {
            get {
                return ResourceManager.GetString("ExItemCantBeComparedIncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified item is already in use..
        /// </summary>
        internal static string ExItemIsInUse {
            get {
                return ResourceManager.GetString("ExItemIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified item is not in use..
        /// </summary>
        internal static string ExItemIsNotInUse {
            get {
                return ResourceManager.GetString("ExItemIsNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified item isn&apos;t pooled..
        /// </summary>
        internal static string ExItemIsNotPooled {
            get {
                return ResourceManager.GetString("ExItemIsNotPooled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified item isn&apos;t found..
        /// </summary>
        internal static string ExItemNotFound {
            get {
                return ResourceManager.GetString("ExItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with name &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ExItemWithNameWasNotFound {
            get {
                return ResourceManager.GetString("ExItemWithNameWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ExItemWithNameXAlreadyExists {
            get {
                return ResourceManager.GetString("ExItemWithNameXAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with Name &apos;{0}&apos; is not found..
        /// </summary>
        internal static string ExItemWithNameXIsNotFound {
            get {
                return ResourceManager.GetString("ExItemWithNameXIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the same key has already been added..
        /// </summary>
        internal static string ExItemWithTheSameKeyHasBeenAdded {
            get {
                return ResourceManager.GetString("ExItemWithTheSameKeyHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key already exists..
        /// </summary>
        internal static string ExKeyAlreadyExists {
            get {
                return ResourceManager.GetString("ExKeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} is not found..
        /// </summary>
        internal static string ExKeyXIsNotFound {
            get {
                return ResourceManager.GetString("ExKeyXIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda parameter &apos;{0}&apos; is out of scope..
        /// </summary>
        internal static string ExLambdaParameterXIsOutOfScope {
            get {
                return ResourceManager.GetString("ExLambdaParameterXIsOutOfScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of the graph depth is exceeded..
        /// </summary>
        internal static string ExLimitOfGraphDepthIsExceeded {
            get {
                return ResourceManager.GetString("ExLimitOfGraphDepthIsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked operation for property {0} missing..
        /// </summary>
        internal static string ExLinkedOperationMissingFormat {
            get {
                return ResourceManager.GetString("ExLinkedOperationMissingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop in action dependency chain is detected..
        /// </summary>
        internal static string ExLoopInActionDependencyChain {
            get {
                return ResourceManager.GetString("ExLoopInActionDependencyChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapping for the property {0} has already been registered..
        /// </summary>
        internal static string ExMappingForPropertyXHasAlreadyBeenRegistered {
            get {
                return ResourceManager.GetString("ExMappingForPropertyXHasAlreadyBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal item count is {0}..
        /// </summary>
        internal static string ExMaxItemCountIsN {
            get {
                return ResourceManager.GetString("ExMaxItemCountIsN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement is already completed..
        /// </summary>
        internal static string ExMeasurementIsAlreadyCompleted {
            get {
                return ResourceManager.GetString("ExMeasurementIsAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement &apos;{0}&apos; must have value..
        /// </summary>
        internal static string ExMeasurementMustHaveValue {
            get {
                return ResourceManager.GetString("ExMeasurementMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member: &apos;{0}&apos; is not a Public Property or Field of Type: &apos;{1}&apos;.
        /// </summary>
        internal static string ExMemberIsNotPublicPropertyOrField {
            get {
                return ResourceManager.GetString("ExMemberIsNotPublicPropertyOrField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge operation require intersection of operands..
        /// </summary>
        internal static string ExMergeOperationRequireIntersectionOfOperands {
            get {
                return ResourceManager.GetString("ExMergeOperationRequireIntersectionOfOperands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinMaxValues aren&apos;t supported for TupleFieldAdvancedComparer..
        /// </summary>
        internal static string ExMinMaxValuesAreNotSupportedForTupleFieldAdvancedComparer {
            get {
                return ResourceManager.GetString("ExMinMaxValuesAreNotSupportedForTupleFieldAdvancedComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model object cannot be removed..
        /// </summary>
        internal static string ExModelObjectCannotBeRemoved {
            get {
                return ResourceManager.GetString("ExModelObjectCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple associates match type &apos;{0}&apos; by its interfaces (at least &apos;{1}&apos; and &apos;{2}&apos;)..
        /// </summary>
        internal static string ExMultipleAssociatesMatch {
            get {
                return ResourceManager.GetString("ExMultipleAssociatesMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: multiple attributes of type &apos;{1}&apos; are not allowed here..
        /// </summary>
        internal static string ExMultipleAttributesOfTypeXAreNotAllowedHere {
            get {
                return ResourceManager.GetString("ExMultipleAttributesOfTypeXAreNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple hints found..
        /// </summary>
        internal static string ExMultipleHintsFound {
            get {
                return ResourceManager.GetString("ExMultipleHintsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple services match to the specified arguments..
        /// </summary>
        internal static string ExMultipleServicesMatchToTheSpecifiedArguments {
            get {
                return ResourceManager.GetString("ExMultipleServicesMatchToTheSpecifiedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested collection is not supported..
        /// </summary>
        internal static string ExNestedCollectionIsNotSupported {
            get {
                return ResourceManager.GetString("ExNestedCollectionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no more available items..
        /// </summary>
        internal static string ExNoAvailableItems {
            get {
                return ResourceManager.GetString("ExNoAvailableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer.Current is null..
        /// </summary>
        internal static string ExNoCurrentComparer {
            get {
                return ResourceManager.GetString("ExNoCurrentComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgarder.Current is null..
        /// </summary>
        internal static string ExNoCurrentUpgrader {
            get {
                return ResourceManager.GetString("ExNoCurrentUpgrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node &quot;{0}&quot; must be processed before being compared as reference (value of &quot;{1}&quot;.{2})..
        /// </summary>
        internal static string ExNodeXMustBeProcessedBeforeBeingComparedAsReferenceValueOfYZ {
            get {
                return ResourceManager.GetString("ExNodeXMustBeProcessedBeforeBeingComparedAsReferenceValueOfYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesting must be created for any node..
        /// </summary>
        internal static string ExNoNesting {
            get {
                return ResourceManager.GetString("ExNoNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no object with specified key..
        /// </summary>
        internal static string ExNoObjectWithSpecifiedKey {
            get {
                return ResourceManager.GetString("ExNoObjectWithSpecifiedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance is not initialized (or not initialized properly)..
        /// </summary>
        internal static string ExNotInitialized {
            get {
                return ResourceManager.GetString("ExNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nullable property {0} is bound to the property {1} that isn&apos;t nullable..
        /// </summary>
        internal static string ExNullablePropertyXIsBoundToPropertyYThatIsNotNullable {
            get {
                return ResourceManager.GetString("ExNullablePropertyXIsBoundToPropertyYThatIsNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is read-only..
        /// </summary>
        internal static string ExObjectIsReadOnly {
            get {
                return ResourceManager.GetString("ExObjectIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only breakable nodes :(.
        /// </summary>
        internal static string ExOnlyBreakableNodesSadSmile {
            get {
                return ResourceManager.GetString("ExOnlyBreakableNodesSadSmile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the normalized expression having the different normal form can be added as the immediate descendant to the root expression..
        /// </summary>
        internal static string ExOnlyNormalizedExpressionCanBeAddedAsChildToRoot {
            get {
                return ResourceManager.GetString("ExOnlyNormalizedExpressionCanBeAddedAsChildToRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one ancestor of each instance of this generic type is allowed..
        /// </summary>
        internal static string ExOnlyOneAncestorOfEachInstanceOfThisGenericTypeIsAllowed {
            get {
                return ResourceManager.GetString("ExOnlyOneAncestorOfEachInstanceOfThisGenericTypeIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation LinkType should be defined before it can be registered in OperationDictionary..
        /// </summary>
        internal static string ExOperationLinkTypeUndefined {
            get {
                return ResourceManager.GetString("ExOperationLinkTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation must be locked before it can be registered in OperationDictionary..
        /// </summary>
        internal static string ExOperationMustBeLocked {
            get {
                return ResourceManager.GetString("ExOperationMustBeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation PropertyName must be specified before it can be registered in OperationDictionary..
        /// </summary>
        internal static string ExOperationPropertyNameUndefined {
            get {
                return ResourceManager.GetString("ExOperationPropertyNameUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node with path &quot;{0}&quot; is not found..
        /// </summary>
        internal static string ExPathXNotFound {
            get {
                return ResourceManager.GetString("ExPathXNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected target model.
        /// </summary>
        internal static string ExpectedTargetModel {
            get {
                return ResourceManager.GetString("ExpectedTargetModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool should be in syncronized mode to utilize AutoCleanup feature..
        /// </summary>
        internal static string ExPoolMustBeSyncronized {
            get {
                return ResourceManager.GetString("ExPoolMustBeSyncronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists in the pool with another key..
        /// </summary>
        internal static string ExPoolWrongKey {
            get {
                return ResourceManager.GetString("ExPoolWrongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port value must be in [0,65535] range..
        /// </summary>
        internal static string ExPortOutOfRange {
            get {
                return ResourceManager.GetString("ExPortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primitive property {0} is bound to the property {1} that isn&apos;t primitive..
        /// </summary>
        internal static string ExPrimitivePropertyXIsBoundToPropertyYThatIsNotPrimitive {
            get {
                return ResourceManager.GetString("ExPrimitivePropertyXIsBoundToPropertyYThatIsNotPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The properties {0} and {1} have different primitive types..
        /// </summary>
        internal static string ExPropertiesXAndYHaveDifferentPrimitiveTypes {
            get {
                return ResourceManager.GetString("ExPropertiesXAndYHaveDifferentPrimitiveTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The properties &quot;{0}&quot; and &quot;{1}&quot; have incompatible types..
        /// </summary>
        internal static string ExPropertiesXAndYHaveIncompatibleTypes {
            get {
                return ResourceManager.GetString("ExPropertiesXAndYHaveIncompatibleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; of type &apos;{1}&apos; does not have public get accessor..
        /// </summary>
        internal static string ExPropertyDoesNotHaveGetter {
            get {
                return ResourceManager.GetString("ExPropertyDoesNotHaveGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; of type &apos;{1}&apos; does not have public set accessor..
        /// </summary>
        internal static string ExPropertyDoesNotHaveSetter {
            get {
                return ResourceManager.GetString("ExPropertyDoesNotHaveSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is already initialized..
        /// </summary>
        internal static string ExPropertyIsAlreadyInitialized {
            get {
                return ResourceManager.GetString("ExPropertyIsAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not initialized (or not initialized properly)..
        /// </summary>
        internal static string ExPropertyIsNotInitialized {
            get {
                return ResourceManager.GetString("ExPropertyIsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property value must belong to the same Model..
        /// </summary>
        internal static string ExPropertyValueMustBelongToTheSameModel {
            get {
                return ResourceManager.GetString("ExPropertyValueMustBelongToTheSameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}.{1}&quot; is not found..
        /// </summary>
        internal static string ExPropertyXYIsNotFound {
            get {
                return ResourceManager.GetString("ExPropertyXYIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range is empty..
        /// </summary>
        internal static string ExRangeIsEmpty {
            get {
                return ResourceManager.GetString("ExRangeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive associate lookup is detected..
        /// </summary>
        internal static string ExRecursiveAssociateLookupDetected {
            get {
                return ResourceManager.GetString("ExRecursiveAssociateLookupDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive constructor paremeter dependency is detected..
        /// </summary>
        internal static string ExRecursiveConstructorParemeterDependencyIsDetected {
            get {
                return ResourceManager.GetString("ExRecursiveConstructorParemeterDependencyIsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string ExReferenceIsAlreadyDefined {
            get {
                return ResourceManager.GetString("ExReferenceIsAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference &apos;{0}&apos; is not resolved yet..
        /// </summary>
        internal static string ExReferenceIsNotResolvedYet {
            get {
                return ResourceManager.GetString("ExReferenceIsNotResolvedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference points to null..
        /// </summary>
        internal static string ExReferenceIsNull {
            get {
                return ResourceManager.GetString("ExReferenceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference property {0} is bound to the property {1} that isn&apos;t reference..
        /// </summary>
        internal static string ExReferencePropertyXIsBoundToPropertyYThatIsNotReference {
            get {
                return ResourceManager.GetString("ExReferencePropertyXIsBoundToPropertyYThatIsNotReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource property {0} is not of string type..
        /// </summary>
        internal static string ExResourcePropertyXIsNotOfStringType {
            get {
                return ResourceManager.GetString("ExResourcePropertyXIsNotOfStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope-bound transaction can be committed only by its scope. Use TransactionScopeBase.Complete() \  Dispose() methods of  appropriate TransactionScopeBase descendant instance to do this..
        /// </summary>
        internal static string ExScopeBoundTransactionCanBeCommittedOnlyByItsScope {
            get {
                return ResourceManager.GetString("ExScopeBoundTransactionCanBeCommittedOnlyByItsScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope can&apos;t be disposed. Most likely it is bound to a different thread..
        /// </summary>
        internal static string ExScopeCantBeDisposed {
            get {
                return ResourceManager.GetString("ExScopeCantBeDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string ExScopeRequired {
            get {
                return ResourceManager.GetString("ExScopeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment is out of range..
        /// </summary>
        internal static string ExSegmentIsOutOfRange {
            get {
                return ResourceManager.GetString("ExSegmentIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; is not found..
        /// </summary>
        internal static string ExServiceNotFound {
            get {
                return ResourceManager.GetString("ExServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service of type &apos;{0}&apos; is not available..
        /// </summary>
        internal static string ExServiceOfTypeXIsNotAvailable {
            get {
                return ResourceManager.GetString("ExServiceOfTypeXIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with name &quot;{0}&quot; of type &apos;{1}&apos; is not available..
        /// </summary>
        internal static string ExServiceWithNameXOfTypeYIsNotAvailable {
            get {
                return ResourceManager.GetString("ExServiceWithNameXOfTypeYIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some operands are not Expressions  of type &apos;System.Boolean&apos;..
        /// </summary>
        internal static string ExSomeOperandsAreNotExpressionsOfTypeBoolean {
            get {
                return ResourceManager.GetString("ExSomeOperandsAreNotExpressionsOfTypeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified capacity value is less than collection count..
        /// </summary>
        internal static string ExSpecifiedCapacityIsLessThenCollectionCount {
            get {
                return ResourceManager.GetString("ExSpecifiedCapacityIsLessThenCollectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified expression can&apos;t be parsed..
        /// </summary>
        internal static string ExSpecifiedExpressionCanNotBeParsed {
            get {
                return ResourceManager.GetString("ExSpecifiedExpressionCanNotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified expression is not a MemberExpression..
        /// </summary>
        internal static string ExSpecifiedExpressionIsNotMemberExpression {
            get {
                return ResourceManager.GetString("ExSpecifiedExpressionIsNotMemberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified type should be either GeneratedTupleDescriptor or its descendant..
        /// </summary>
        internal static string ExSpecifiedTypeShouldBeGeneratedTupleDescriptorOrItsDescendant {
            get {
                return ResourceManager.GetString("ExSpecifiedTypeShouldBeGeneratedTupleDescriptorOrItsDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String does not correspond to the specified descriptor..
        /// </summary>
        internal static string ExStringDoesNotCorrespondToDescriptor {
            get {
                return ResourceManager.GetString("ExStringDoesNotCorrespondToDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System date \ time has been changed..
        /// </summary>
        internal static string ExSystemTimeChanged {
            get {
                return ResourceManager.GetString("ExSystemTimeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object already exists: &quot;{0}&quot;. To assign a new one, you must remove the old one first..
        /// </summary>
        internal static string ExTargetObjectExistsX {
            get {
                return ResourceManager.GetString("ExTargetObjectExistsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of sources is too small. Expected number is {0}..
        /// </summary>
        internal static string ExTheNumberOfSourcesIsTooSmallExpected {
            get {
                return ResourceManager.GetString("ExTheNumberOfSourcesIsTooSmallExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed for the parameter context operating with expected values of parameters..
        /// </summary>
        internal static string ExThisOperationIsNotAllowedForParameterContextOperatingWithExpectedValuesOfParameters {
            get {
                return ResourceManager.GetString("ExThisOperationIsNotAllowedForParameterContextOperatingWithExpectedValuesOfParame" +
                        "ters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is already activated..
        /// </summary>
        internal static string ExTransactionIsAlreadyActivated {
            get {
                return ResourceManager.GetString("ExTransactionIsAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionScope.IsCompleted can not be set to &apos;false&apos;..
        /// </summary>
        internal static string ExTransactionScopeIsCompletedCanNotBeSetToFalse {
            get {
                return ResourceManager.GetString("ExTransactionScopeIsCompletedCanNotBeSetToFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not supported by BinaryPrimitiveSerializer..
        /// </summary>
        internal static string ExTypeIsNotSupportedByBinaryPrimitiveSerializer {
            get {
                return ResourceManager.GetString("ExTypeIsNotSupportedByBinaryPrimitiveSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of {0} property must be {1}..
        /// </summary>
        internal static string ExTypeOfXPropertyMustBeY {
            get {
                return ResourceManager.GetString("ExTypeOfXPropertyMustBeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} can&apos;t be transformed..
        /// </summary>
        internal static string ExTypeXCanNotBeTransformed {
            get {
                return ResourceManager.GetString("ExTypeXCanNotBeTransformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have property &apos;{1}&apos;..
        /// </summary>
        internal static string ExTypeXDoesNotHavePropertyY {
            get {
                return ResourceManager.GetString("ExTypeXDoesNotHavePropertyY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} has already been registered..
        /// </summary>
        internal static string ExTypeXHasAlreadyBeenRegistered {
            get {
                return ResourceManager.GetString("ExTypeXHasAlreadyBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} hasn&apos;t been registered..
        /// </summary>
        internal static string ExTypeXHasNotBeenRegistered {
            get {
                return ResourceManager.GetString("ExTypeXHasNotBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} isn&apos;t a subclass of the type {1}..
        /// </summary>
        internal static string ExTypeXIsNotSubclassOfTypeY {
            get {
                return ResourceManager.GetString("ExTypeXIsNotSubclassOfTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must be non-abstract type..
        /// </summary>
        internal static string ExTypeXMustBeNonAbstractType {
            get {
                return ResourceManager.GetString("ExTypeXMustBeNonAbstractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must be reference type..
        /// </summary>
        internal static string ExTypeXMustBeReferenceType {
            get {
                return ResourceManager.GetString("ExTypeXMustBeReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must implement &apos;{1}&apos;, or must be its descendant..
        /// </summary>
        internal static string ExTypeXMustImplementY {
            get {
                return ResourceManager.GetString("ExTypeXMustImplementY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} should not be generic..
        /// </summary>
        internal static string ExTypeXShouldNotBeGeneric {
            get {
                return ResourceManager.GetString("ExTypeXShouldNotBeGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to bind parameters to lambda {0}. Parameters count is incorrect..
        /// </summary>
        internal static string ExUnableToBindParametersToLambdaXParametersCountIsIncorrect {
            get {
                return ResourceManager.GetString("ExUnableToBindParametersToLambdaXParametersCountIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast null value to {0}; use {0}? instead..
        /// </summary>
        internal static string ExUnableToCastNullValueToXUseXInstead {
            get {
                return ResourceManager.GetString("ExUnableToCastNullValueToXUseXInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create provider instance. Check if provider&apos;s class has static &quot;Instance&quot; property..
        /// </summary>
        internal static string ExUnableToCreateProviderInstance {
            get {
                return ResourceManager.GetString("ExUnableToCreateProviderInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to use expression {0} as {1} parameter of lambda {2} because of type mistmatch..
        /// </summary>
        internal static string ExUnableToUseExpressionXAsXParameterOfLambdaXBecauseOfTypeMistmatch {
            get {
                return ResourceManager.GetString("ExUnableToUseExpressionXAsXParameterOfLambdaXBecauseOfTypeMistmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown expression type: &apos;{0} ({1})&apos;.
        /// </summary>
        internal static string ExUnknownExpressionType {
            get {
                return ResourceManager.GetString("ExUnknownExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade sequence validation failure..
        /// </summary>
        internal static string ExUpgradeSequenceValidationFailure {
            get {
                return ResourceManager.GetString("ExUpgradeSequenceValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use LogCaptureScope constructor instead..
        /// </summary>
        internal static string ExUseLogCaptureScopeConstructorInstead {
            get {
                return ResourceManager.GetString("ExUseLogCaptureScopeConstructorInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use LogIndentScope constructor instead..
        /// </summary>
        internal static string ExUseLogIndentScopeConstructorInstead {
            get {
                return ResourceManager.GetString("ExUseLogIndentScopeConstructorInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for parameter &apos;{0}&apos; is not set..
        /// </summary>
        internal static string ExValueForParameterXIsNotSet {
            get {
                return ResourceManager.GetString("ExValueForParameterXIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not available..
        /// </summary>
        internal static string ExValueIsNotAvailable {
            get {
                return ResourceManager.GetString("ExValueIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value with name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ExValueWithNameXAlreadyExists {
            get {
                return ResourceManager.GetString("ExValueWithNameXAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value with name &apos;{0}&apos; is not found..
        /// </summary>
        internal static string ExValueWithNameXIsNotFound {
            get {
                return ResourceManager.GetString("ExValueWithNameXIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not allowed or invalid here..
        /// </summary>
        internal static string ExValueXIsNotAllowedHere {
            get {
                return ResourceManager.GetString("ExValueXIsNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source collection contains at least one item of type &quot;{0}&quot;, that cannot be cast to the item type of the destination collection..
        /// </summary>
        internal static string ExWrongSourceCollectionElementType {
            get {
                return ResourceManager.GetString("ExWrongSourceCollectionElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is neither class nor value type..
        /// </summary>
        internal static string ExXIsNeitherClassNorValueType {
            get {
                return ResourceManager.GetString("ExXIsNeitherClassNorValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (v{1}).
        /// </summary>
        internal static string HasVersionFormat {
            get {
                return ResourceManager.GetString("HasVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}d.
        /// </summary>
        internal static string InfinitesimalFormat {
            get {
                return ResourceManager.GetString("InfinitesimalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inf.
        /// </summary>
        internal static string Infinity {
            get {
                return ResourceManager.GetString("Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} change(s).
        /// </summary>
        internal static string ItemChangeCountFormat {
            get {
                return ResourceManager.GetString("ItemChangeCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ItemChangeFormat {
            get {
                return ResourceManager.GetString("ItemChangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use disposed instance of type &apos;{0}&apos;..
        /// </summary>
        internal static string LogAttemptToUseDisposedInstance {
            get {
                return ResourceManager.GetString("LogAttemptToUseDisposedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic upgrade sequence validation.
        /// </summary>
        internal static string LogAutomaticUpgradeSequenceValidation {
            get {
                return ResourceManager.GetString("LogAutomaticUpgradeSequenceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find {0} (&apos;{1}&apos;) for type &apos;{2}&apos;..
        /// </summary>
        internal static string LogCantFindAssociateFor {
            get {
                return ResourceManager.GetString("LogCantFindAssociateFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!.
        /// </summary>
        internal static string LogException {
            get {
                return ResourceManager.GetString("LogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&lt;{1}, {2}&gt;&apos; creation has failed for &apos;{3}&apos;..
        /// </summary>
        internal static string LogGenericAssociateCreationHasFailedFor {
            get {
                return ResourceManager.GetString("LogGenericAssociateCreationHasFailedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&lt;{1}, {2}&gt;&apos; was used for &apos;{3}&apos;..
        /// </summary>
        internal static string LogGenericAssociateIsUsedFor {
            get {
                return ResourceManager.GetString("LogGenericAssociateIsUsedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        internal static string LogItemFormat {
            get {
                return ResourceManager.GetString("LogItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: started..
        /// </summary>
        internal static string LogRegionBegin {
            get {
                return ResourceManager.GetString("LogRegionBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: completed..
        /// </summary>
        internal static string LogRegionEnd {
            get {
                return ResourceManager.GetString("LogRegionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe dispose of &apos;{0}&apos; failing..
        /// </summary>
        internal static string LogSafeDisposeFailing {
            get {
                return ResourceManager.GetString("LogSafeDisposeFailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope dispose error..
        /// </summary>
        internal static string LogScopeDisposeError {
            get {
                return ResourceManager.GetString("LogScopeDisposeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get default hasher for type {0}.
        /// </summary>
        internal static string LogUnableToGetDefaultHasherForTypeXxx {
            get {
                return ResourceManager.GetString("LogUnableToGetDefaultHasherForTypeXxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed..
        /// </summary>
        internal static string LogValidationFailed {
            get {
                return ResourceManager.GetString("LogValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string NodeInfoFormat {
            get {
                return ResourceManager.GetString("NodeInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n\a.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original exception(s).
        /// </summary>
        internal static string OriginalExceptions {
            get {
                return ResourceManager.GetString("OriginalExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, {1}).
        /// </summary>
        internal static string PairFormat {
            get {
                return ResourceManager.GetString("PairFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}: {1}.
        /// </summary>
        internal static string PropertyChangeFormat {
            get {
                return ResourceManager.GetString("PropertyChangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read-only.
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r/o.
        /// </summary>
        internal static string ReadOnlyShort {
            get {
                return ResourceManager.GetString("ReadOnlyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read-write.
        /// </summary>
        internal static string ReadWrite {
            get {
                return ResourceManager.GetString("ReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r/w.
        /// </summary>
        internal static string ReadWriteShort {
            get {
                return ResourceManager.GetString("ReadWriteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recursive.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #({0}).
        /// </summary>
        internal static string ReferenceFormat {
            get {
                return ResourceManager.GetString("ReferenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {6:s} @{1,-5} {2,5} {3,-24} {4}{5}.
        /// </summary>
        internal static string ReleaseLogFormat {
            get {
                return ResourceManager.GetString("ReleaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversed({0}).
        /// </summary>
        internal static string ReversedFormat {
            get {
                return ResourceManager.GetString("ReversedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0} ... {1}].
        /// </summary>
        internal static string SegmentFormat {
            get {
                return ResourceManager.GetString("SegmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type=&apos;{0}&apos;, #=&apos;{1}&apos; ({2}).
        /// </summary>
        internal static string SerializationDataFormat {
            get {
                return ResourceManager.GetString("SerializationDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}: {5}.
        /// </summary>
        internal static string SimpleLogFormat {
            get {
                return ResourceManager.GetString("SimpleLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreadSafeCached({0}).
        /// </summary>
        internal static string ThreadSafeCachedFormat {
            get {
                return ResourceManager.GetString("ThreadSafeCachedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} of ({2}).
        /// </summary>
        internal static string TransformedTupleFormat {
            get {
                return ResourceManager.GetString("TransformedTupleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, {1}, {2}).
        /// </summary>
        internal static string TripletFormat {
            get {
                return ResourceManager.GetString("TripletFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TupleDescriptor({0}).
        /// </summary>
        internal static string TupleDescriptorFormat {
            get {
                return ResourceManager.GetString("TupleDescriptorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string TupleFormat {
            get {
                return ResourceManager.GetString("TupleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}).
        /// </summary>
        internal static string TupleTransformFormat {
            get {
                return ResourceManager.GetString("TupleTransformFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to dispose an item when disposable container has an invalid state..
        /// </summary>
        internal static string UnableToDisposeItemWhenContainerIsNotDisposed {
            get {
                return ResourceManager.GetString("UnableToDisposeItemWhenContainerIsNotDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade sequence.
        /// </summary>
        internal static string UpgradeSequence {
            get {
                return ResourceManager.GetString("UpgradeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1}.
        /// </summary>
        internal static string XInY {
            get {
                return ResourceManager.GetString("XInY", resourceCulture);
            }
        }
    }
}
