//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtensive.Modelling.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtensive.Modelling.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding has failed for {0}. Check property declaration..
        /// </summary>
        internal static string ExBindingFailedForX {
            get {
                return ResourceManager.GetString("ExBindingFailedForX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find a constructor to execute {0}..
        /// </summary>
        internal static string ExCannotFindConstructorToExecuteX {
            get {
                return ResourceManager.GetString("ExCannotFindConstructorToExecuteX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid node state..
        /// </summary>
        internal static string ExInvalidNodeState {
            get {
                return ResourceManager.GetString("ExInvalidNodeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parent value..
        /// </summary>
        internal static string ExInvalidParentValue {
            get {
                return ResourceManager.GetString("ExInvalidParentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists..
        /// </summary>
        internal static string ExItemAlreadyExists {
            get {
                return ResourceManager.GetString("ExItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ExItemWithNameXAlreadyExists {
            get {
                return ResourceManager.GetString("ExItemWithNameXAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with Name &apos;{0}&apos; is not found..
        /// </summary>
        internal static string ExItemWithNameXIsNotFound {
            get {
                return ResourceManager.GetString("ExItemWithNameXIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model object cannot be removed..
        /// </summary>
        internal static string ExModelObjectCannotBeRemoved {
            get {
                return ResourceManager.GetString("ExModelObjectCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple hints found..
        /// </summary>
        internal static string ExMultipleHintsFound {
            get {
                return ResourceManager.GetString("ExMultipleHintsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesting must be created for any node..
        /// </summary>
        internal static string ExNoNesting {
            get {
                return ResourceManager.GetString("ExNoNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node with path &quot;{0}&quot; is not found..
        /// </summary>
        internal static string ExPathXNotFound {
            get {
                return ResourceManager.GetString("ExPathXNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object already exists: &quot;{0}&quot;. To assign a new one, you must remove the old one first..
        /// </summary>
        internal static string ExTargetObjectExistsX {
            get {
                return ResourceManager.GetString("ExTargetObjectExistsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of {0} property must be {1}..
        /// </summary>
        internal static string ExTypeOfXPropertyMustBeY {
            get {
                return ResourceManager.GetString("ExTypeOfXPropertyMustBeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string NodeInfoFormat {
            get {
                return ResourceManager.GetString("NodeInfoFormat", resourceCulture);
            }
        }
    }
}
