/*
 Creation of main database for tests
*/

CREATE DATABASE [DO-Tests] ON  PRIMARY 
( NAME = N'DO-Tests', FILENAME = N'/var/opt/mssql/data/DO-Tests.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests_log', FILENAME = N'/var/opt/mssql/data/DO-Tests_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests] SET RECOVERY SIMPLE
GO
ALTER DATABASE [DO-Tests] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO


/*
Creation of additional databases, used in multidatabase tests
*/

/* DO-Tests-1 */

CREATE DATABASE [DO-Tests-1] ON  PRIMARY 
( NAME = N'DO-Tests-1', FILENAME = N'/var/opt/mssql/data/DO-Tests-1.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-1_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-1_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-1] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-1] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-1] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-1] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-1] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-1] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-1] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-1] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-1]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-1] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO


/* DO-Tests-2 */

CREATE DATABASE [DO-Tests-2] ON  PRIMARY 
( NAME = N'DO-Tests-2', FILENAME = N'/var/opt/mssql/data/DO-Tests-2.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-2_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-2_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-2] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-2] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-2] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-2] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-2] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-2] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-2] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-2] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-2]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-2] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO


/* DO-Tests-3 */

CREATE DATABASE [DO-Tests-3] ON  PRIMARY 
( NAME = N'DO-Tests-3', FILENAME = N'/var/opt/mssql/data/DO-Tests-3.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-3_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-3_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-3] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-3] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-3] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-3] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-3] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-3] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-3] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-3] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-3] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-3] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-3] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-3] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-3] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-3] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-3] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-3] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-3] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-3] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-3] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-3] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-3] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-3] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-3]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-3] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO


/* DO-Tests-4 */

CREATE DATABASE [DO-Tests-4] ON  PRIMARY 
( NAME = N'DO-Tests-4', FILENAME = N'/var/opt/mssql/data/DO-Tests-4.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-4_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-4_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-4] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-4] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-4] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-4] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-4] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-4] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-4] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-4] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-4] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-4] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-4] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-4] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-4] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-4] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-4] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-4] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-4] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-4] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-4] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-4] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-4] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-4] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-4]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-4] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO

/* DO-Tests-5 */

CREATE DATABASE [DO-Tests-5] ON  PRIMARY 
( NAME = N'DO-Tests-5', FILENAME = N'/var/opt/mssql/data/DO-Tests-5.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-5_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-5_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-5] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-5] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-5] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-5] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-5] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-5] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-5] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-5] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-5] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-5] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-5] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-5] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-5] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-5] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-5] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-5] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-5] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-5] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-5] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-5] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-5] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-5] SET PAGE_VERIFY CHECKSUM  
GO

USE [DO-Tests-5]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-5] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO

/* DO-Tests-6 */

CREATE DATABASE [DO-Tests-6] ON  PRIMARY 
( NAME = N'DO-Tests-6', FILENAME = N'/var/opt/mssql/data/DO-Tests-6.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-6_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-6_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-6] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-6] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-6] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-6] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-6] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-6] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-6] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-6] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-6] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-6] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-6] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-6] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-6] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-6] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-6] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-6] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-6] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-6] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-6] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-6] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-6] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-6] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-6] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-6] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-6] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-6] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-6]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-6] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO

/* DO-Tests-7 */

CREATE DATABASE [DO-Tests-7] ON  PRIMARY 
( NAME = N'DO-Tests-7', FILENAME = N'/var/opt/mssql/data/DO-Tests-7.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-7_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-7_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-7] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-7] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-7] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-7] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-7] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-7] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-7] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-7] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-7] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-7] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-7] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-7] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-7] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-7] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-7] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-7] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-7] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-7] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-7] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-7] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-7] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-7] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-7] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-7] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-7] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-7] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-7]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-7] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO

/* DO-Tests-8 */

CREATE DATABASE [DO-Tests-8] ON  PRIMARY 
( NAME = N'DO-Tests-8', FILENAME = N'/var/opt/mssql/data/DO-Tests-8.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-8_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-8_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-8] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-8] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-8] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-8] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-8] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-8] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-8] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-8] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-8] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-8] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-8] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-8] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-8] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-8] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-8] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-8] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-8] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-8] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-8] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-8] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-8] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-8] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-8] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-8] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-8] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-8] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-8]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-8] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO

/* DO-Tests-9 */

CREATE DATABASE [DO-Tests-9] ON  PRIMARY 
( NAME = N'DO-Tests-9', FILENAME = N'/var/opt/mssql/data/DO-Tests-9.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-9_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-9_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-9] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-9] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-9] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-9] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-9] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-9] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-9] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-9] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-9] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-9] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-9] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-9] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-9] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-9] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-9] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-9] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-9] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-9] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-9] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-9] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-9] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-9] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-9] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-9] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-9] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-9] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-9]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-9] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO

/* DO-Tests-10 */

CREATE DATABASE [DO-Tests-10] ON  PRIMARY 
( NAME = N'DO-Tests-10', FILENAME = N'/var/opt/mssql/data/DO-Tests-10.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-10_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-10_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-10] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-10] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-10] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-10] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-10] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-10] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-10] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-10] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-10] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-10] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-10] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-10] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-10] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-10] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-10] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-10] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-10] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-10] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-10] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-10] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-10] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-10] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-10] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-10] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-10] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-10] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-10]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-10] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO

/* DO-Tests-11 */

CREATE DATABASE [DO-Tests-11] ON  PRIMARY 
( NAME = N'DO-Tests-11', FILENAME = N'/var/opt/mssql/data/DO-Tests-11.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-11_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-11_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-11] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-11] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-11] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-11] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-11] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-11] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-11] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-11] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-11] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-11] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-11] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-11] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-11] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-11] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-11] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-11] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-11] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-11] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-11] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-11] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-11] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-11] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-11] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-11] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-11] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-11] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-11]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-11] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO

/* DO-Tests-12 */

CREATE DATABASE [DO-Tests-12] ON  PRIMARY 
( NAME = N'DO-Tests-12', FILENAME = N'/var/opt/mssql/data/DO-Tests-12.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DO-Tests-12_log', FILENAME = N'/var/opt/mssql/data/DO-Tests-12_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DO-Tests-12] SET COMPATIBILITY_LEVEL = 140 
GO
ALTER DATABASE [DO-Tests-12] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DO-Tests-12] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DO-Tests-12] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DO-Tests-12] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DO-Tests-12] SET ARITHABORT OFF 
GO
ALTER DATABASE [DO-Tests-12] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DO-Tests-12] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DO-Tests-12] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DO-Tests-12] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DO-Tests-12] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DO-Tests-12] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DO-Tests-12] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DO-Tests-12] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DO-Tests-12] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DO-Tests-12] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DO-Tests-12] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DO-Tests-12] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DO-Tests-12] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DO-Tests-12] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DO-Tests-12] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DO-Tests-12] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DO-Tests-12] SET  READ_WRITE 
GO
ALTER DATABASE [DO-Tests-12] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DO-Tests-12] SET  MULTI_USER 
GO
ALTER DATABASE [DO-Tests-12] SET PAGE_VERIFY CHECKSUM  
GO
USE [DO-Tests-12]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DO-Tests-12] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
/* creation of schemas for multischema tests */
CREATE SCHEMA [Model1] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model2] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model3] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model4] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model5] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model6] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model7] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model8] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model9] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model10] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model11] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [Model12] AUTHORIZATION [dbo];
GO



/*
Creation of logins
  dotest user for general tests
  readonlydotest for tests that read-only user
*/

USE [master]
GO
CREATE LOGIN [dotest] WITH PASSWORD=N'dotest', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [DO-Tests]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-1]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-1]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-2]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-2]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-3]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-3]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-4]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-4]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-5]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-5]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-6]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-6]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-7]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-7]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-8]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-8]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-9]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-9]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-10]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-10]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-11]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-11]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

USE [DO-Tests-12]
GO
CREATE USER [dotest] FOR LOGIN [dotest]
GO
USE [DO-Tests-12]
GO
ALTER USER [dotest] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_owner', N'dotest'
GO

/* user for certain tests where only reading of data needed */

USE [master]
GO
CREATE LOGIN [readonlydotest] WITH PASSWORD=N'readonlydotest', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [DO-Tests]
GO
CREATE USER [readonlydotest] FOR LOGIN [readonlydotest]
GO
USE [DO-Tests]
GO
ALTER USER [readonlydotest] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [DO-Tests]
GO
EXEC sp_addrolemember N'db_datareader', N'readonlydotest'
GO
USE [DO-Tests]
GO
EXEC sp_addrolemember N'db_denydatawriter', N'readonlydotest'
GO
USE [DO-Tests-1]
GO
CREATE USER [readonlydotest] FOR LOGIN [readonlydotest]
GO
USE [DO-Tests-1]
GO
ALTER USER [readonlydotest] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [DO-Tests-1]
GO
EXEC sp_addrolemember N'db_datareader', N'readonlydotest'
GO
USE [DO-Tests-1]
GO
EXEC sp_addrolemember N'db_denydatawriter', N'readonlydotest'
GO
USE [DO-Tests-2]
GO
CREATE USER [readonlydotest] FOR LOGIN [readonlydotest]
GO
USE [DO-Tests-2]
GO
ALTER USER [readonlydotest] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [DO-Tests-2]
GO
EXEC sp_addrolemember N'db_datareader', N'readonlydotest'
GO
USE [DO-Tests-2]
GO
EXEC sp_addrolemember N'db_denydatawriter', N'readonlydotest'
GO
USE [DO-Tests-3]
GO
CREATE USER [readonlydotest] FOR LOGIN [readonlydotest]
GO
USE [DO-Tests-3]
GO
ALTER USER [readonlydotest] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [DO-Tests-3]
GO
EXEC sp_addrolemember N'db_datareader', N'readonlydotest'
GO
USE [DO-Tests-3]
GO
EXEC sp_addrolemember N'db_denydatawriter', N'readonlydotest'
GO
USE [DO-Tests-4]
GO
CREATE USER [readonlydotest] FOR LOGIN [readonlydotest]
GO
USE [DO-Tests-4]
GO
ALTER USER [readonlydotest] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [DO-Tests-4]
GO
EXEC sp_addrolemember N'db_datareader', N'readonlydotest'
GO
USE [DO-Tests-4]
GO
EXEC sp_addrolemember N'db_denydatawriter', N'readonlydotest'
GO


/* Full-text intexes initialization */

USE [DO-Tests]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests_dbo]
CREATE FULLTEXT CATALOG [DO-Tests_Model1]
CREATE FULLTEXT CATALOG [DO-Tests_Model2]
CREATE FULLTEXT CATALOG [DO-Tests_Model3]
CREATE FULLTEXT CATALOG [DO-Tests_Model4]
CREATE FULLTEXT CATALOG [DO-Tests_Model5]
CREATE FULLTEXT CATALOG [DO-Tests_Model6]
CREATE FULLTEXT CATALOG [DO-Tests_Model7]
CREATE FULLTEXT CATALOG [DO-Tests_Model8]
CREATE FULLTEXT CATALOG [DO-Tests_Model9]
CREATE FULLTEXT CATALOG [DO-Tests_Model10]
CREATE FULLTEXT CATALOG [DO-Tests_Model11]
CREATE FULLTEXT CATALOG [DO-Tests_Model12]
GO

USE [DO-Tests-1]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-1_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-1_Model12]
GO

USE [DO-Tests-2]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-2_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-2_Model12]
GO

USE [DO-Tests-3]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-3_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-3_Model12]
GO

USE [DO-Tests-4]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-4_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-4_Model12]
GO

USE [DO-Tests-5]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-5_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-5_Model12]
GO

use [DO-Tests-6]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-6_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-6_Model12]
GO

USE [DO-Tests-7]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-7_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-7_Model12]
GO

USE [DO-Tests-8]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-8_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-8_Model12]
GO

USE [DO-Tests-9]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-9_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-9_Model12]

USE [DO-Tests-10]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-10_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-10_Model12]
GO

USE [DO-Tests-11]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-11_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-11_Model12]
GO

USE [DO-Tests-12]
CREATE FULLTEXT CATALOG DO_FT AS DEFAULT
CREATE FULLTEXT CATALOG [DO-Tests-12_dbo]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model1]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model2]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model3]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model4]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model5]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model6]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model7]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model8]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model9]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model10]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model11]
CREATE FULLTEXT CATALOG [DO-Tests-12_Model12]
