//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtensive.Storage.Rse.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtensive.Storage.Rse.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate &apos;{0}&apos; is not supported for type &apos;{1}&apos;.
        /// </summary>
        internal static string ExAggregateXIsNotSupportedForTypeY {
            get {
                return ResourceManager.GetString("ExAggregateXIsNotSupportedForTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one column index pair must be specified..
        /// </summary>
        internal static string ExAtLeastOneColumnIndexPairMustBeSpecified {
            get {
                return ResourceManager.GetString("ExAtLeastOneColumnIndexPairMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t compile - active CompilationContext has no Compiler (Compiler is null)..
        /// </summary>
        internal static string ExCanNotCompileNoCompiler {
            get {
                return ResourceManager.GetString("ExCanNotCompileNoCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t compile - no active EnumerationContext exists..
        /// </summary>
        internal static string ExCanNotCompileNoEnumerationContext {
            get {
                return ResourceManager.GetString("ExCanNotCompileNoEnumerationContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t compile the provider &apos;{0}&apos;..
        /// </summary>
        internal static string ExCantCompileProviderX {
            get {
                return ResourceManager.GetString("ExCantCompileProviderX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t convert the {0} to the {1}..
        /// </summary>
        internal static string ExCantConvertXToY {
            get {
                return ResourceManager.GetString("ExCantConvertXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open EnumerationScope, since there is no current CompilationContext..
        /// </summary>
        internal static string ExCantOpenEnumerationScopeSinceThereIsNoCurrentCompilationContext {
            get {
                return ResourceManager.GetString("ExCantOpenEnumerationScopeSinceThereIsNoCurrentCompilationContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column group could not be found..
        /// </summary>
        internal static string ExColumnGroupCouldNotBeFound {
            get {
                return ResourceManager.GetString("ExColumnGroupCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns used by the CalculatedColumn&apos;s expression containing the ApplyParameter are removed..
        /// </summary>
        internal static string ExColumnsUsedByCalculatedColumnExpressionContainingApplyParameterAreRemoved {
            get {
                return ResourceManager.GetString("ExColumnsUsedByCalculatedColumnExpressionContainingApplyParameterAreRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns used by the predicate containing ApplyParameter are removed..
        /// </summary>
        internal static string ExColumnsUsedByPredicateContainingApplyParameterAreRemoved {
            get {
                return ResourceManager.GetString("ExColumnsUsedByPredicateContainingApplyParameterAreRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current compiler is not suitable for this operation, most likely there is no active Session..
        /// </summary>
        internal static string ExCurrentCompilerIsNotSuitableForThisOperationMostLikelyThereIsNoActiveSession {
            get {
                return ResourceManager.GetString("ExCurrentCompilerIsNotSuitableForThisOperationMostLikelyThereIsNoActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter tuple descriptor mistmatches with source mapping descriptor..
        /// </summary>
        internal static string ExFilterTupleDescriptorMistmatchesWithSourceMappingDescriptor {
            get {
                return ResourceManager.GetString("ExFilterTupleDescriptorMistmatchesWithSourceMappingDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field name &apos;{0}&apos;..
        /// </summary>
        internal static string ExInvalidFieldNameX {
            get {
                return ResourceManager.GetString("ExInvalidFieldNameX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The normalized boolean expression must be the root expression..
        /// </summary>
        internal static string ExNormalizedExpressionMustBeRoot {
            get {
                return ResourceManager.GetString("ExNormalizedExpressionMustBeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The normalized boolean expression must have the &apos;{0}&apos; form..
        /// </summary>
        internal static string ExNormalizedExpressionMustHaveXForm {
            get {
                return ResourceManager.GetString("ExNormalizedExpressionMustHaveXForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The normalized boolean expression must not be the root expression..
        /// </summary>
        internal static string ExNormalizedExpressionMustNotBeRoot {
            get {
                return ResourceManager.GetString("ExNormalizedExpressionMustNotBeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single-column key supported..
        /// </summary>
        internal static string ExOnlySingleColumnKeySupported {
            get {
                return ResourceManager.GetString("ExOnlySingleColumnKeySupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ordering of records is not specified for RowNumberProvider..
        /// </summary>
        internal static string ExOrderingOfRecordsIsNotSpecifiedForRowNumberProvider {
            get {
                return ResourceManager.GetString("ExOrderingOfRecordsIsNotSpecifiedForRowNumberProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order key not found in mapping..
        /// </summary>
        internal static string ExOrderKeyNotFoundInMapping {
            get {
                return ResourceManager.GetString("ExOrderKeyNotFoundInMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not a tuple access expression.
        /// </summary>
        internal static string ExParameterXIsNotATupleAccessExpression {
            get {
                return ResourceManager.GetString("ExParameterXIsNotATupleAccessExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate contains accesses to different ApplyParameters..
        /// </summary>
        internal static string ExPredicateContainsAccessesToDifferentApplyParameters {
            get {
                return ResourceManager.GetString("ExPredicateContainsAccessesToDifferentApplyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider must be either CompilableProvider or ExecutableProvider.
        /// </summary>
        internal static string ExProviderMustBeEitherCompilableProviderOrExecutableProvider {
            get {
                return ResourceManager.GetString("ExProviderMustBeEitherCompilableProviderOrExecutableProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SelectProvider removes columns used for an ordering..
        /// </summary>
        internal static string ExSelectProviderRemovesColumnsUsedForOrdering {
            get {
                return ResourceManager.GetString("ExSelectProviderRemovesColumnsUsedForOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains more than one element..
        /// </summary>
        internal static string ExSequenceContainsMoreThanOneElement {
            get {
                return ResourceManager.GetString("ExSequenceContainsMoreThanOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the expression&apos;s return value is not &apos;{0}&apos;..
        /// </summary>
        internal static string ExTypeOfExpressionReturnValueIsNotX {
            get {
                return ResourceManager.GetString("ExTypeOfExpressionReturnValueIsNotX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize JoinIndexProvider. Columns count mismatch..
        /// </summary>
        internal static string ExUnableToInitializeJoinIndexProviderColumnsCountMismatch {
            get {
                return ResourceManager.GetString("ExUnableToInitializeJoinIndexProviderColumnsCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is already assigned.
        /// </summary>
        internal static string ExValueIsAlreadyAssigned {
            get {
                return ResourceManager.GetString("ExValueIsAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the parameter {0} can&apos;t be {1}, if the value of the parameter {2} is {3}..
        /// </summary>
        internal static string ExValueOfParameterWCantBeXIfValueOfParameterYIsZ {
            get {
                return ResourceManager.GetString("ExValueOfParameterWCantBeXIfValueOfParameterYIsZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be executed on specified sources..
        /// </summary>
        internal static string ExXCantBeExecuted {
            get {
                return ResourceManager.GetString("ExXCantBeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be active..
        /// </summary>
        internal static string ExXMustBeActive {
            get {
                return ResourceManager.GetString("ExXMustBeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowNumber{0}.
        /// </summary>
        internal static string RowNumberX {
            get {
                return ResourceManager.GetString("RowNumberX", resourceCulture);
            }
        }
    }
}
