// Copyright (C) 2007 Xtensive LLC.
// All rights reserved.
// For conditions of distribution and use, see license.

using System;

namespace Xtensive.Sql
{
  [Serializable]
  public enum SqlNodeType
  {
    Action,
    Add,
    All,
    Alter,
    And,
    Any,
    Array,
    Assign,
    Asterisk,
    Avg,
    Batch,
    BeginEndBlock,
    Between,
    BitAnd,
    BitNot,
    BitOr,
    BitXor,
    Break,
    Case,
    Cast,
    CloseCursor,
    Collate,
    Column,
    ColumnRef,
    Concat,
    Conditional,
    Constant,
    Continue,
    Container,
    Count,
    Create,
    Cursor,
    DeclareCursor,
    DefaultValue,
    Delete,
    Divide,
    Drop,
    /// <summary>
    /// Raw concatenation binary expression. Just concates both underlying expressions 
    /// without any additional sign between.
    /// </summary>
    RawConcat,
    Equals,
    Except,
    Exists,
    Fetch,
    FunctionCall,
    Grant,
    GreaterThan,
    GreaterThanOrEquals,
    In,
    Insert,
    Intersect,
    IsNull,
    Join,
    Hint,
    LessThan,
    LessThanOrEquals,
    Like,
    Literal,
    Match,
    Max,
    Min,
    Modulo,
    Multiply,
    NextValue,
    Not,
    NotBetween,
    NotEquals,
    NotIn,
    Negate,
    Null,
    OpenCursor,
    Or,
    Order,
    Overlaps,
    Parameter,
    Revoke,
    Row,
    Select,
    SetDefault,
    Some,
    SubSelect,
    Subtract,
    Sum,
    Table,
    Trim,
    Union,
    Unique,
    Update,
    Variable,
    Variant,
    DeclareVariable,
    While,
  }
}