// Copyright (C) 2007 Xtensive LLC.
// All rights reserved.
// For conditions of distribution and use, see license.

using System;

namespace Xtensive.Sql
{
  [Serializable]
  public enum SqlNodeType
  {
    Action,
    Add,
//    Alias,
//    AliasRef,
    All,
    Alter,
    And,
    Any,
    Array,
    Assign,
    Asterisk,
    Avg,
    Batch,
    BeginEndBlock,
    Between,
    BitAnd,
    BitNot,
    BitOr,
    BitXor,
    Break,
    Case,
    Cast,
//    ClientArray,
//    ClientCase,
//    ClientCollection,
//    ClientElement,
//    ClientExpression,
//    ClientParameter,
    CloseCursor,
//    Coalesce,
    Collate,
    Column,
    ColumnRef,
    Concat,
    Conditional,
    Constant,
    Continue,
    Container,
//    Convert,
    Count,
//    Covar,
    Create,
    Cursor,
    DeclareCursor,
    DefaultValue,
    Delete,
    Divide,
//    DoNotVisit,
    Drop,
//    Element,
//    ExprSet,

    /// <summary>
    /// Raw concatenation binary expression. Just concates both underlying expressions 
    /// without any additional sign between.
    /// </summary>
    RawConcat,
    Equals,
    Except,
    Exists,
    Fetch,
    FunctionCall,
//    TableValuedFunctionCall,
//    IncludeMember,
//    Including,
    Grant,
    GreaterThan,
    GreaterThanOrEquals,
    In,
    Insert,
    Intersect,
    IsNull,
    Join,
    Hint,
    LessThan,
    LessThanOrEquals,
//    Link,
//    List,
    Like,
    Literal,
//    LongCount,
//    Grouping,
    Match,
    Max,
//    MethodCall,
//    Member,
//    MemberAssign,
    Min,
    Modulo,
    Multiply,
    NextValue,
//    Multiset,
//    Name,
//    NamedExpression,
    Not,
    NotBetween,
    NotEquals,
    NotIn,
    Negate,
    Null,
//    New,
//    Nop,
    OpenCursor,
    Or,
    Order,
//    OptionalValue,
    Overlaps,
//    QueryOption,
//    QuerySet,
    Parameter,
//    Property,
//    Reference,
//    ReferencePoint,
    Revoke,
    Row,
//    ScalarSubSelect,
//    SearchedCase,
    Select,
    SetDefault,
//    SimpleCase,
    Some,
//    Stddev,
//    SubExpression,
//    SubExpressionRef,
    SubSelect,
    Subtract,
    Sum,
    Table,
    Trim,
//    TypeCase,
    Union,
    Unique,
    Update,
//    UserColumn,
//    UserQuery,
//    UserRow,
    Variable,
    Variant,
    DeclareVariable,
//    ValueOf,
//    When,
    While,
  }
}