name: Bump package version
on:
  workflow_dispatch:
    inputs: []
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump
        run: gawk -i inplace '{match($0,/(^.+DoVersion>[0-9]+.[0-9]+.[0-9]+.)([0-9]+)/,a);if(a[2]>0){print a[1]a[2]+1"</DoVersion>"}else{print $0}}' Version.props
      - name: Commit
        run: git commit -a -m 'Bump version' && git push
