name: 🛠🐘 PostgreSQL 9.x tests
run-name: Run database tests on PostgreSQL on dispatch. Run No ${{ github.run_number }}.
on:
  workflow_dispatch:
    inputs:
      fetch_depth:
        description: 'Depth of repo fetch (change if SHA populated)'
        required: false
        default: 1
        type: number
      specific_sha:
        description: 'Commit SHA to checkout'
        required: false
        default: ''
        type: string
      pgsql91:
        description: 'PostgreSQL 9.1'
        type: boolean
        default: false
        required: true
      pgsql92:
        description: 'PostgreSQL 9.2'
        type: boolean
        default: false
        required: true
      pgsql96:
        description: 'PostgreSQL 9.6'
        type: boolean
        default: true
        required: true

# new commits with the same key will cancel previously run workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  # requires special docker registry because the image is based on schema 1, which is depricated
  #test_on_pgsql90:
  #  name: Tests on PostgreSQL 9.0
  #  if: ${{ inputs.pgsql90 }}
  #  uses: DataObjects-NET/dataobjects-net/.github/workflows/reusable-storage-dependant-tests.yml@7.1
  #  with:
  #    storage: pgsql90
  #    build_config: Release
  #    target_frameworks: net6.0
  #    specific_sha: ${{ inputs.specific_sha }}
  #    fetch_depth: 1
  #    test_output_verbosity: minimal
  #    test_run_timeout: 70
  #    run_main: true
  #    run_sql: true
  #    run_extensions: true
  #    publish_raw_results: false

  test_on_pgsql91:
    name: Tests on PostgreSQL 9.1
    if: ${{ inputs.pgsql91 }}
    strategy:
      matrix:
        net: [ 'net5.0', 'net6.0' ]
    uses: DataObjects-NET/dataobjects-net/.github/workflows/reusable-storage-dependant-tests.yml@7.1
    with:
      storage: pgsql91
      build_config: Release
      target_framework: ${{ matrix.net }}
      specific_sha: ${{ inputs.specific_sha }}
      fetch_depth: ${{ fromJSON(inputs.fetch_depth) }}
      test_output_verbosity: minimal
      test_run_timeout: 30
      run_main: true
      run_sql: true
      run_extensions: true
      publish_raw_results: false

  test_on_pgsql92:
    name: Tests on PostgreSQL 9.2
    if: ${{ inputs.pgsql92 }}
    strategy:
      matrix:
        net: [ 'net5.0', 'net6.0' ]
    uses: DataObjects-NET/dataobjects-net/.github/workflows/reusable-storage-dependant-tests.yml@7.1
    with:
      storage: pgsql92
      build_config: Release
      target_framework: ${{ matrix.net }}
      specific_sha: ${{ inputs.specific_sha }}
      fetch_depth: ${{ fromJSON(inputs.fetch_depth) }}
      test_output_verbosity: minimal
      test_run_timeout: 30
      run_main: true
      run_sql: true
      run_extensions: true
      publish_raw_results: false

  test_on_pgsql96:
    name: Tests on PostgreSQL 9.6
    if: ${{ inputs.pgsql96 }}
    strategy:
      matrix:
        net: [ 'net5.0', 'net6.0' ]
    uses: DataObjects-NET/dataobjects-net/.github/workflows/reusable-storage-dependant-tests.yml@7.1
    with:
      storage: pgsql96
      build_config: Release
      target_framework: ${{ matrix.net }}
      specific_sha: ${{ inputs.specific_sha }}
      fetch_depth: ${{ fromJSON(inputs.fetch_depth) }}
      test_output_verbosity: minimal
      test_run_timeout: 30
      run_main: true
      run_sql: true
      run_extensions: true
      publish_raw_results: false
