name: Tests with SQL Server
on:
  pull_request:
    branches: [ master-servicetitan ]
env:
  DO_CONFIG_FILE: "/tmp/do-test.cfg"
  DO_TargetFrameworks: net7.0
  SQL_PASSWD: dbatools.I0
jobs:
  test-with-sql:
    name: SQL tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: { dotnet-version: 7 }
      - name: Build SQL Docker image with FTS feature
        run: docker build -t sql .github/actions/mssql-fts
      - name: Run SQL Server container
        run: docker run -e ACCEPT_EULA=Y -e MSSQL_PID='Developer' -e MSSQL_SA_PASSWORD=${SQL_PASSWD} -p 1433:1433 -d sql
      - name: Build
        run: dotnet build -v q Orm.sln
      - name: Init Test DB
        run: sqlcmd -U sa -P $SQL_PASSWD -C -i Orm/Xtensive.Orm.Tests.Framework/DO-Tests.sql && sqlcmd -U sa -P $SQL_PASSWD -C -i Orm/Xtensive.Orm.Tests.Framework/DO-Tests-Plus.sql
      - name: Create DO Tests Config file
        run: echo default=sqlserver://sa:${SQL_PASSWD}@localhost/DO-Tests?MultipleActiveResultSets=True >$DO_CONFIG_FILE
      - name: Tests
        run: dotnet test --no-build -v n Orm/Xtensive.Orm.Tests/Xtensive.Orm.Tests.csproj --filter 'TestCategory!=Mute'


